-- This file was auto-generated by YML2HDL toll.
-- https://gitlab.com/tcpaiva/yml2hdl

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use ieee.math_real.all;

library shared_lib;
use shared_lib.common_ieee_pkg.all;
use shared_lib.l0mdt_constants_pkg.all;
use shared_lib.l0mdt_dataformats_pkg.all;
use shared_lib.common_constants_pkg.all;
use shared_lib.common_types_pkg.all;
--library heg_lib;
--use heg_lib.heg_pkg.all;
library hegtypes_lib;
use hegtypes_lib.heg_pkg.all;

package ult_tb_sim_pkg is

  type input_mdt_rt is record
    ToA : unsigned(64-1 downto 0);
    station : unsigned(8-1 downto 0);
    chamber : unsigned(SLC_CHAMBER_LEN-1 downto 0);
    event : unsigned(32-1 downto 0);
    tdc : tdcpolmux2tar_rt;
  end record input_mdt_rt;
  constant INPUT_MDT_LEN : integer := 150;
  subtype input_mdt_rvt is std_logic_vector(INPUT_MDT_LEN-1 downto 0);
  function vectorify(x: input_mdt_rt) return input_mdt_rvt;
  function structify(x: input_mdt_rvt) return input_mdt_rt;
  function nullify(x: input_mdt_rt) return input_mdt_rt;

  constant TB_TAR_FIFO_WIDTH : integer := 32;

  type input_mdt_bus_at is array(TB_TAR_FIFO_WIDTH-1 downto 0) of input_mdt_rt;
  type input_mdt_bus_avt is array(TB_TAR_FIFO_WIDTH-1 downto 0) of input_mdt_rvt;
  function vectorify(x: input_mdt_bus_at) return input_mdt_bus_avt;
  function vectorify(x: input_mdt_bus_at) return std_logic_vector;
  function structify(x: input_mdt_bus_avt) return input_mdt_bus_at;
  function structify(x: std_logic_vector) return input_mdt_bus_at;
  function nullify(x: input_mdt_bus_at) return input_mdt_bus_at;
  function nullify(x: input_mdt_bus_avt) return input_mdt_bus_avt;

  type tar2hps_tb_at is array(TB_TAR_FIFO_WIDTH-1 downto 0) of tar2hps_rt;
  type tar2hps_tb_avt is array(TB_TAR_FIFO_WIDTH-1 downto 0) of tar2hps_rvt;
  function vectorify(x: tar2hps_tb_at) return tar2hps_tb_avt;
  function vectorify(x: tar2hps_tb_at) return std_logic_vector;
  function structify(x: tar2hps_tb_avt) return tar2hps_tb_at;
  function structify(x: std_logic_vector) return tar2hps_tb_at;
  function nullify(x: tar2hps_tb_at) return tar2hps_tb_at;
  function nullify(x: tar2hps_tb_avt) return tar2hps_tb_avt;

  type pol2tar_tb_at is array(TB_TAR_FIFO_WIDTH-1 downto 0) of tdcpolmux2tar_rt;
  type pol2tar_tb_avt is array(TB_TAR_FIFO_WIDTH-1 downto 0) of tdcpolmux2tar_rvt;
  function vectorify(x: pol2tar_tb_at) return pol2tar_tb_avt;
  function vectorify(x: pol2tar_tb_at) return std_logic_vector;
  function structify(x: pol2tar_tb_avt) return pol2tar_tb_at;
  function structify(x: std_logic_vector) return pol2tar_tb_at;
  function nullify(x: pol2tar_tb_at) return pol2tar_tb_at;
  function nullify(x: pol2tar_tb_avt) return pol2tar_tb_avt;

  type input_slc_rt is record
    ToA : unsigned(64-1 downto 0);
    event : unsigned(32-1 downto 0);
    slc : slc_rx_rt;
  end record input_slc_rt;
  constant INPUT_SLC_LEN : integer := 252;
  subtype input_slc_rvt is std_logic_vector(INPUT_SLC_LEN-1 downto 0);
  function vectorify(x: input_slc_rt) return input_slc_rvt;
  function structify(x: input_slc_rvt) return input_slc_rt;
  function nullify(x: input_slc_rt) return input_slc_rt;

  constant TB_SLC_FIFO_WIDTH : integer := 32;

  type input_slc_bus_at is array(TB_SLC_FIFO_WIDTH-1 downto 0) of input_slc_rt;
  type input_slc_bus_avt is array(TB_SLC_FIFO_WIDTH-1 downto 0) of input_slc_rvt;
  function vectorify(x: input_slc_bus_at) return input_slc_bus_avt;
  function vectorify(x: input_slc_bus_at) return std_logic_vector;
  function structify(x: input_slc_bus_avt) return input_slc_bus_at;
  function structify(x: std_logic_vector) return input_slc_bus_at;
  function nullify(x: input_slc_bus_at) return input_slc_bus_at;
  function nullify(x: input_slc_bus_avt) return input_slc_bus_avt;

  type slc_tb_at is array(TB_SLC_FIFO_WIDTH-1 downto 0) of slc_rx_rt;
  type slc_tb_avt is array(TB_SLC_FIFO_WIDTH-1 downto 0) of slc_rx_rvt;
  function vectorify(x: slc_tb_at) return slc_tb_avt;
  function vectorify(x: slc_tb_at) return std_logic_vector;
  function structify(x: slc_tb_avt) return slc_tb_at;
  function structify(x: std_logic_vector) return slc_tb_at;
  function nullify(x: slc_tb_at) return slc_tb_at;
  function nullify(x: slc_tb_avt) return slc_tb_avt;

  type out_heg_bm_hit_sim_rt is record
    ToA : unsigned(64-1 downto 0);
    station : unsigned(4-1 downto 0);
    thread : unsigned(4-1 downto 0);
    data : heg2sfhit_rt;
  end record out_heg_bm_hit_sim_rt;
  constant OUT_HEG_BM_HIT_SIM_LEN : integer := 113;
  subtype out_heg_bm_hit_sim_rvt is std_logic_vector(OUT_HEG_BM_HIT_SIM_LEN-1 downto 0);
  function vectorify(x: out_heg_bm_hit_sim_rt) return out_heg_bm_hit_sim_rvt;
  function structify(x: out_heg_bm_hit_sim_rvt) return out_heg_bm_hit_sim_rt;
  function nullify(x: out_heg_bm_hit_sim_rt) return out_heg_bm_hit_sim_rt;

  type out_heg_bm_slc_sim_rt is record
    ToA : unsigned(64-1 downto 0);
    station : unsigned(4-1 downto 0);
    thread : unsigned(4-1 downto 0);
    data : heg2sfslc_rt;
  end record out_heg_bm_slc_sim_rt;
  constant OUT_HEG_BM_SLC_SIM_LEN : integer := 149;
  subtype out_heg_bm_slc_sim_rvt is std_logic_vector(OUT_HEG_BM_SLC_SIM_LEN-1 downto 0);
  function vectorify(x: out_heg_bm_slc_sim_rt) return out_heg_bm_slc_sim_rvt;
  function structify(x: out_heg_bm_slc_sim_rvt) return out_heg_bm_slc_sim_rt;
  function nullify(x: out_heg_bm_slc_sim_rt) return out_heg_bm_slc_sim_rt;

  type out_heg_bm_ctrl_sim_rt is record
    ToA : unsigned(64-1 downto 0);
    station : unsigned(4-1 downto 0);
    thread : unsigned(4-1 downto 0);
    heg_ctrl : heg_ctrl2sf_rt;
    data : heg2sfslc_rt;
  end record out_heg_bm_ctrl_sim_rt;
  constant OUT_HEG_BM_CTRL_SIM_LEN : integer := 152;
  subtype out_heg_bm_ctrl_sim_rvt is std_logic_vector(OUT_HEG_BM_CTRL_SIM_LEN-1 downto 0);
  function vectorify(x: out_heg_bm_ctrl_sim_rt) return out_heg_bm_ctrl_sim_rvt;
  function structify(x: out_heg_bm_ctrl_sim_rvt) return out_heg_bm_ctrl_sim_rt;
  function nullify(x: out_heg_bm_ctrl_sim_rt) return out_heg_bm_ctrl_sim_rt;

  type in_pt_pt2sf_sim_rt is record
    ToA : unsigned(64-1 downto 0);
    station : unsigned(4-1 downto 0);
    thread : unsigned(4-1 downto 0);
    data : sf2ptcalc_rt;
  end record in_pt_pt2sf_sim_rt;
  constant IN_PT_PT2SF_SIM_LEN : integer := 136;
  subtype in_pt_pt2sf_sim_rvt is std_logic_vector(IN_PT_PT2SF_SIM_LEN-1 downto 0);
  function vectorify(x: in_pt_pt2sf_sim_rt) return in_pt_pt2sf_sim_rvt;
  function structify(x: in_pt_pt2sf_sim_rvt) return in_pt_pt2sf_sim_rt;
  function nullify(x: in_pt_pt2sf_sim_rt) return in_pt_pt2sf_sim_rt;

  type in_pt_mpl_sim_rt is record
    ToA : unsigned(64-1 downto 0);
    thread : unsigned(4-1 downto 0);
    data : pl2ptcalc_rt;
  end record in_pt_mpl_sim_rt;
  constant IN_PT_MPL_SIM_LEN : integer := 126;
  subtype in_pt_mpl_sim_rvt is std_logic_vector(IN_PT_MPL_SIM_LEN-1 downto 0);
  function vectorify(x: in_pt_mpl_sim_rt) return in_pt_mpl_sim_rvt;
  function structify(x: in_pt_mpl_sim_rvt) return in_pt_mpl_sim_rt;
  function nullify(x: in_pt_mpl_sim_rt) return in_pt_mpl_sim_rt;

  type in_mtc_pt_sim_rt is record
    ToA : unsigned(64-1 downto 0);
    thread : unsigned(4-1 downto 0);
    data : ptcalc2mtc_rt;
  end record in_mtc_pt_sim_rt;
  constant IN_MTC_PT_SIM_LEN : integer := 122;
  subtype in_mtc_pt_sim_rvt is std_logic_vector(IN_MTC_PT_SIM_LEN-1 downto 0);
  function vectorify(x: in_mtc_pt_sim_rt) return in_mtc_pt_sim_rvt;
  function structify(x: in_mtc_pt_sim_rvt) return in_mtc_pt_sim_rt;
  function nullify(x: in_mtc_pt_sim_rt) return in_mtc_pt_sim_rt;

  type in_mtc_mpl_sim_rt is record
    ToA : unsigned(64-1 downto 0);
    thread : unsigned(4-1 downto 0);
    data : pl2mtc_rt;
  end record in_mtc_mpl_sim_rt;
  constant IN_MTC_MPL_SIM_LEN : integer := 181;
  subtype in_mtc_mpl_sim_rvt is std_logic_vector(IN_MTC_MPL_SIM_LEN-1 downto 0);
  function vectorify(x: in_mtc_mpl_sim_rt) return in_mtc_mpl_sim_rvt;
  function structify(x: in_mtc_mpl_sim_rvt) return in_mtc_mpl_sim_rt;
  function nullify(x: in_mtc_mpl_sim_rt) return in_mtc_mpl_sim_rt;

end package ult_tb_sim_pkg;

------------------------------------------------------------

package body ult_tb_sim_pkg is

  function vectorify(x: input_mdt_rt) return input_mdt_rvt is
    variable y : input_mdt_rvt;
  begin
    y(149 downto 86)           := vectorify(x.ToA);
    y(85 downto 78)            := vectorify(x.station);
    y(77 downto 74)            := vectorify(x.chamber);
    y(73 downto 42)            := vectorify(x.event);
    y(41 downto 0)             := vectorify(x.tdc);
    return y;
  end function vectorify;
  function structify(x: input_mdt_rvt) return input_mdt_rt is
    variable y : input_mdt_rt;
  begin
    y.ToA                      := structify(x(149 downto 86));
    y.station                  := structify(x(85 downto 78));
    y.chamber                  := structify(x(77 downto 74));
    y.event                    := structify(x(73 downto 42));
    y.tdc                      := structify(x(41 downto 0));
    return y;
  end function structify;
  function nullify(x: input_mdt_rt) return input_mdt_rt is
    variable y : input_mdt_rt;
  begin
    y.ToA                      := nullify(x.ToA);
    y.station                  := nullify(x.station);
    y.chamber                  := nullify(x.chamber);
    y.event                    := nullify(x.event);
    y.tdc                      := nullify(x.tdc);
    return y;
  end function nullify;

  function vectorify(x: input_mdt_bus_at) return input_mdt_bus_avt is
    variable y :  input_mdt_bus_avt;
  begin
    l: for i in x'range loop
      y(i) := vectorify(x(i));
    end loop l;
    return y;
  end function vectorify;
  function vectorify(x: input_mdt_bus_at) return std_logic_vector is
    variable msb : integer := x'length*150-1;
    variable y : std_logic_vector(msb downto 0);
  begin
    l: for i in x'range loop
      y(msb downto msb-150+1) := vectorify(x(i));
      msb := msb - 150;
    end loop l;
    return y;
  end function vectorify;
  function structify(x: input_mdt_bus_avt) return input_mdt_bus_at is
    variable y :  input_mdt_bus_at;
  begin
    l: for i in x'range loop
      y(i) := structify(x(i));
    end loop l;
    return y;
  end function structify;
  function structify(x: std_logic_vector) return input_mdt_bus_at is
    variable y :  input_mdt_bus_at;
    variable msb : integer := x'left;
  begin
    l: for i in y'range loop
      y(i) := structify(x(msb downto msb-150+1));
      msb := msb - 150;
    end loop l;
    return y;
  end function structify;
  function nullify(x: input_mdt_bus_at) return input_mdt_bus_at is
    variable y :  input_mdt_bus_at;
  begin
    l: for i in y'range loop
      y(i) := nullify(x(i));
    end loop l;
    return y;
  end function nullify;
  function nullify(x: input_mdt_bus_avt) return input_mdt_bus_avt is
    variable y :  input_mdt_bus_avt;
  begin
    l: for i in y'range loop
      y(i) := nullify(x(i));
    end loop l;
    return y;
  end function nullify;

  function vectorify(x: tar2hps_tb_at) return tar2hps_tb_avt is
    variable y :  tar2hps_tb_avt;
  begin
    l: for i in x'range loop
      y(i) := vectorify(x(i));
    end loop l;
    return y;
  end function vectorify;
  function vectorify(x: tar2hps_tb_at) return std_logic_vector is
    variable msb : integer := x'length*36-1;
    variable y : std_logic_vector(msb downto 0);
  begin
    l: for i in x'range loop
      y(msb downto msb-36+1) := vectorify(x(i));
      msb := msb - 36;
    end loop l;
    return y;
  end function vectorify;
  function structify(x: tar2hps_tb_avt) return tar2hps_tb_at is
    variable y :  tar2hps_tb_at;
  begin
    l: for i in x'range loop
      y(i) := structify(x(i));
    end loop l;
    return y;
  end function structify;
  function structify(x: std_logic_vector) return tar2hps_tb_at is
    variable y :  tar2hps_tb_at;
    variable msb : integer := x'left;
  begin
    l: for i in y'range loop
      y(i) := structify(x(msb downto msb-36+1));
      msb := msb - 36;
    end loop l;
    return y;
  end function structify;
  function nullify(x: tar2hps_tb_at) return tar2hps_tb_at is
    variable y :  tar2hps_tb_at;
  begin
    l: for i in y'range loop
      y(i) := nullify(x(i));
    end loop l;
    return y;
  end function nullify;
  function nullify(x: tar2hps_tb_avt) return tar2hps_tb_avt is
    variable y :  tar2hps_tb_avt;
  begin
    l: for i in y'range loop
      y(i) := nullify(x(i));
    end loop l;
    return y;
  end function nullify;

  function vectorify(x: pol2tar_tb_at) return pol2tar_tb_avt is
    variable y :  pol2tar_tb_avt;
  begin
    l: for i in x'range loop
      y(i) := vectorify(x(i));
    end loop l;
    return y;
  end function vectorify;
  function vectorify(x: pol2tar_tb_at) return std_logic_vector is
    variable msb : integer := x'length*42-1;
    variable y : std_logic_vector(msb downto 0);
  begin
    l: for i in x'range loop
      y(msb downto msb-42+1) := vectorify(x(i));
      msb := msb - 42;
    end loop l;
    return y;
  end function vectorify;
  function structify(x: pol2tar_tb_avt) return pol2tar_tb_at is
    variable y :  pol2tar_tb_at;
  begin
    l: for i in x'range loop
      y(i) := structify(x(i));
    end loop l;
    return y;
  end function structify;
  function structify(x: std_logic_vector) return pol2tar_tb_at is
    variable y :  pol2tar_tb_at;
    variable msb : integer := x'left;
  begin
    l: for i in y'range loop
      y(i) := structify(x(msb downto msb-42+1));
      msb := msb - 42;
    end loop l;
    return y;
  end function structify;
  function nullify(x: pol2tar_tb_at) return pol2tar_tb_at is
    variable y :  pol2tar_tb_at;
  begin
    l: for i in y'range loop
      y(i) := nullify(x(i));
    end loop l;
    return y;
  end function nullify;
  function nullify(x: pol2tar_tb_avt) return pol2tar_tb_avt is
    variable y :  pol2tar_tb_avt;
  begin
    l: for i in y'range loop
      y(i) := nullify(x(i));
    end loop l;
    return y;
  end function nullify;

  function vectorify(x: input_slc_rt) return input_slc_rvt is
    variable y : input_slc_rvt;
  begin
    y(251 downto 188)          := vectorify(x.ToA);
    y(187 downto 156)          := vectorify(x.event);
    y(155 downto 0)            := vectorify(x.slc);
    return y;
  end function vectorify;
  function structify(x: input_slc_rvt) return input_slc_rt is
    variable y : input_slc_rt;
  begin
    y.ToA                      := structify(x(251 downto 188));
    y.event                    := structify(x(187 downto 156));
    y.slc                      := structify(x(155 downto 0));
    return y;
  end function structify;
  function nullify(x: input_slc_rt) return input_slc_rt is
    variable y : input_slc_rt;
  begin
    y.ToA                      := nullify(x.ToA);
    y.event                    := nullify(x.event);
    y.slc                      := nullify(x.slc);
    return y;
  end function nullify;

  function vectorify(x: input_slc_bus_at) return input_slc_bus_avt is
    variable y :  input_slc_bus_avt;
  begin
    l: for i in x'range loop
      y(i) := vectorify(x(i));
    end loop l;
    return y;
  end function vectorify;
  function vectorify(x: input_slc_bus_at) return std_logic_vector is
    variable msb : integer := x'length*252-1;
    variable y : std_logic_vector(msb downto 0);
  begin
    l: for i in x'range loop
      y(msb downto msb-252+1) := vectorify(x(i));
      msb := msb - 252;
    end loop l;
    return y;
  end function vectorify;
  function structify(x: input_slc_bus_avt) return input_slc_bus_at is
    variable y :  input_slc_bus_at;
  begin
    l: for i in x'range loop
      y(i) := structify(x(i));
    end loop l;
    return y;
  end function structify;
  function structify(x: std_logic_vector) return input_slc_bus_at is
    variable y :  input_slc_bus_at;
    variable msb : integer := x'left;
  begin
    l: for i in y'range loop
      y(i) := structify(x(msb downto msb-252+1));
      msb := msb - 252;
    end loop l;
    return y;
  end function structify;
  function nullify(x: input_slc_bus_at) return input_slc_bus_at is
    variable y :  input_slc_bus_at;
  begin
    l: for i in y'range loop
      y(i) := nullify(x(i));
    end loop l;
    return y;
  end function nullify;
  function nullify(x: input_slc_bus_avt) return input_slc_bus_avt is
    variable y :  input_slc_bus_avt;
  begin
    l: for i in y'range loop
      y(i) := nullify(x(i));
    end loop l;
    return y;
  end function nullify;

  function vectorify(x: slc_tb_at) return slc_tb_avt is
    variable y :  slc_tb_avt;
  begin
    l: for i in x'range loop
      y(i) := vectorify(x(i));
    end loop l;
    return y;
  end function vectorify;
  function vectorify(x: slc_tb_at) return std_logic_vector is
    variable msb : integer := x'length*156-1;
    variable y : std_logic_vector(msb downto 0);
  begin
    l: for i in x'range loop
      y(msb downto msb-156+1) := vectorify(x(i));
      msb := msb - 156;
    end loop l;
    return y;
  end function vectorify;
  function structify(x: slc_tb_avt) return slc_tb_at is
    variable y :  slc_tb_at;
  begin
    l: for i in x'range loop
      y(i) := structify(x(i));
    end loop l;
    return y;
  end function structify;
  function structify(x: std_logic_vector) return slc_tb_at is
    variable y :  slc_tb_at;
    variable msb : integer := x'left;
  begin
    l: for i in y'range loop
      y(i) := structify(x(msb downto msb-156+1));
      msb := msb - 156;
    end loop l;
    return y;
  end function structify;
  function nullify(x: slc_tb_at) return slc_tb_at is
    variable y :  slc_tb_at;
  begin
    l: for i in y'range loop
      y(i) := nullify(x(i));
    end loop l;
    return y;
  end function nullify;
  function nullify(x: slc_tb_avt) return slc_tb_avt is
    variable y :  slc_tb_avt;
  begin
    l: for i in y'range loop
      y(i) := nullify(x(i));
    end loop l;
    return y;
  end function nullify;

  function vectorify(x: out_heg_bm_hit_sim_rt) return out_heg_bm_hit_sim_rvt is
    variable y : out_heg_bm_hit_sim_rvt;
  begin
    y(112 downto 49)           := vectorify(x.ToA);
    y(48 downto 45)            := vectorify(x.station);
    y(44 downto 41)            := vectorify(x.thread);
    y(40 downto 0)             := vectorify(x.data);
    return y;
  end function vectorify;
  function structify(x: out_heg_bm_hit_sim_rvt) return out_heg_bm_hit_sim_rt is
    variable y : out_heg_bm_hit_sim_rt;
  begin
    y.ToA                      := structify(x(112 downto 49));
    y.station                  := structify(x(48 downto 45));
    y.thread                   := structify(x(44 downto 41));
    y.data                     := structify(x(40 downto 0));
    return y;
  end function structify;
  function nullify(x: out_heg_bm_hit_sim_rt) return out_heg_bm_hit_sim_rt is
    variable y : out_heg_bm_hit_sim_rt;
  begin
    y.ToA                      := nullify(x.ToA);
    y.station                  := nullify(x.station);
    y.thread                   := nullify(x.thread);
    y.data                     := nullify(x.data);
    return y;
  end function nullify;

  function vectorify(x: out_heg_bm_slc_sim_rt) return out_heg_bm_slc_sim_rvt is
    variable y : out_heg_bm_slc_sim_rvt;
  begin
    y(148 downto 85)           := vectorify(x.ToA);
    y(84 downto 81)            := vectorify(x.station);
    y(80 downto 77)            := vectorify(x.thread);
    y(76 downto 0)             := vectorify(x.data);
    return y;
  end function vectorify;
  function structify(x: out_heg_bm_slc_sim_rvt) return out_heg_bm_slc_sim_rt is
    variable y : out_heg_bm_slc_sim_rt;
  begin
    y.ToA                      := structify(x(148 downto 85));
    y.station                  := structify(x(84 downto 81));
    y.thread                   := structify(x(80 downto 77));
    y.data                     := structify(x(76 downto 0));
    return y;
  end function structify;
  function nullify(x: out_heg_bm_slc_sim_rt) return out_heg_bm_slc_sim_rt is
    variable y : out_heg_bm_slc_sim_rt;
  begin
    y.ToA                      := nullify(x.ToA);
    y.station                  := nullify(x.station);
    y.thread                   := nullify(x.thread);
    y.data                     := nullify(x.data);
    return y;
  end function nullify;

  function vectorify(x: out_heg_bm_ctrl_sim_rt) return out_heg_bm_ctrl_sim_rvt is
    variable y : out_heg_bm_ctrl_sim_rvt;
  begin
    y(151 downto 88)           := vectorify(x.ToA);
    y(87 downto 84)            := vectorify(x.station);
    y(83 downto 80)            := vectorify(x.thread);
    y(79 downto 77)            := vectorify(x.heg_ctrl);
    y(76 downto 0)             := vectorify(x.data);
    return y;
  end function vectorify;
  function structify(x: out_heg_bm_ctrl_sim_rvt) return out_heg_bm_ctrl_sim_rt is
    variable y : out_heg_bm_ctrl_sim_rt;
  begin
    y.ToA                      := structify(x(151 downto 88));
    y.station                  := structify(x(87 downto 84));
    y.thread                   := structify(x(83 downto 80));
    y.heg_ctrl                 := structify(x(79 downto 77));
    y.data                     := structify(x(76 downto 0));
    return y;
  end function structify;
  function nullify(x: out_heg_bm_ctrl_sim_rt) return out_heg_bm_ctrl_sim_rt is
    variable y : out_heg_bm_ctrl_sim_rt;
  begin
    y.ToA                      := nullify(x.ToA);
    y.station                  := nullify(x.station);
    y.thread                   := nullify(x.thread);
    y.heg_ctrl                 := nullify(x.heg_ctrl);
    y.data                     := nullify(x.data);
    return y;
  end function nullify;

  function vectorify(x: in_pt_pt2sf_sim_rt) return in_pt_pt2sf_sim_rvt is
    variable y : in_pt_pt2sf_sim_rvt;
  begin
    y(135 downto 72)           := vectorify(x.ToA);
    y(71 downto 68)            := vectorify(x.station);
    y(67 downto 64)            := vectorify(x.thread);
    y(63 downto 0)             := vectorify(x.data);
    return y;
  end function vectorify;
  function structify(x: in_pt_pt2sf_sim_rvt) return in_pt_pt2sf_sim_rt is
    variable y : in_pt_pt2sf_sim_rt;
  begin
    y.ToA                      := structify(x(135 downto 72));
    y.station                  := structify(x(71 downto 68));
    y.thread                   := structify(x(67 downto 64));
    y.data                     := structify(x(63 downto 0));
    return y;
  end function structify;
  function nullify(x: in_pt_pt2sf_sim_rt) return in_pt_pt2sf_sim_rt is
    variable y : in_pt_pt2sf_sim_rt;
  begin
    y.ToA                      := nullify(x.ToA);
    y.station                  := nullify(x.station);
    y.thread                   := nullify(x.thread);
    y.data                     := nullify(x.data);
    return y;
  end function nullify;

  function vectorify(x: in_pt_mpl_sim_rt) return in_pt_mpl_sim_rvt is
    variable y : in_pt_mpl_sim_rvt;
  begin
    y(125 downto 62)           := vectorify(x.ToA);
    y(61 downto 58)            := vectorify(x.thread);
    y(57 downto 0)             := vectorify(x.data);
    return y;
  end function vectorify;
  function structify(x: in_pt_mpl_sim_rvt) return in_pt_mpl_sim_rt is
    variable y : in_pt_mpl_sim_rt;
  begin
    y.ToA                      := structify(x(125 downto 62));
    y.thread                   := structify(x(61 downto 58));
    y.data                     := structify(x(57 downto 0));
    return y;
  end function structify;
  function nullify(x: in_pt_mpl_sim_rt) return in_pt_mpl_sim_rt is
    variable y : in_pt_mpl_sim_rt;
  begin
    y.ToA                      := nullify(x.ToA);
    y.thread                   := nullify(x.thread);
    y.data                     := nullify(x.data);
    return y;
  end function nullify;

  function vectorify(x: in_mtc_pt_sim_rt) return in_mtc_pt_sim_rvt is
    variable y : in_mtc_pt_sim_rvt;
  begin
    y(121 downto 58)           := vectorify(x.ToA);
    y(57 downto 54)            := vectorify(x.thread);
    y(53 downto 0)             := vectorify(x.data);
    return y;
  end function vectorify;
  function structify(x: in_mtc_pt_sim_rvt) return in_mtc_pt_sim_rt is
    variable y : in_mtc_pt_sim_rt;
  begin
    y.ToA                      := structify(x(121 downto 58));
    y.thread                   := structify(x(57 downto 54));
    y.data                     := structify(x(53 downto 0));
    return y;
  end function structify;
  function nullify(x: in_mtc_pt_sim_rt) return in_mtc_pt_sim_rt is
    variable y : in_mtc_pt_sim_rt;
  begin
    y.ToA                      := nullify(x.ToA);
    y.thread                   := nullify(x.thread);
    y.data                     := nullify(x.data);
    return y;
  end function nullify;

  function vectorify(x: in_mtc_mpl_sim_rt) return in_mtc_mpl_sim_rvt is
    variable y : in_mtc_mpl_sim_rvt;
  begin
    y(180 downto 117)          := vectorify(x.ToA);
    y(116 downto 113)          := vectorify(x.thread);
    y(112 downto 0)            := vectorify(x.data);
    return y;
  end function vectorify;
  function structify(x: in_mtc_mpl_sim_rvt) return in_mtc_mpl_sim_rt is
    variable y : in_mtc_mpl_sim_rt;
  begin
    y.ToA                      := structify(x(180 downto 117));
    y.thread                   := structify(x(116 downto 113));
    y.data                     := structify(x(112 downto 0));
    return y;
  end function structify;
  function nullify(x: in_mtc_mpl_sim_rt) return in_mtc_mpl_sim_rt is
    variable y : in_mtc_mpl_sim_rt;
  begin
    y.ToA                      := nullify(x.ToA);
    y.thread                   := nullify(x.thread);
    y.data                     := nullify(x.data);
    return y;
  end function nullify;

end package body ult_tb_sim_pkg;
