#################### BA3_hps_csf_bp_inn Project ###########################
GEN:BA3_hps_csf_bp_inn:
    extends: .generate_project
    variables:
      extends: .vars
      PROJECT_NAME: MainBlocks/BA3_hps_csf_bp_inn
      HOG_ONLY_SYNTH: 0 # if 1 runs only the synthesis
      
    tags:
      - normal-ops
      - hog
      # - "2020.2"


# SIM:BA3_hps_csf_bp_inn_vivado:
#     extends: .simulate_project
#     variables:
#       extends: .vars
#       PROJECT_NAME: MainBlocks/BA3_hps_csf_bp_inn

SIM:BA3_hps_csf_bp_inn_questa:
    extends: .simulate_project
    variables:
      extends: .vars
      PROJECT_NAME: MainBlocks/BA3_hps_csf_bp_inn

SIM:BA3_hps_csf_bp_inn_riviera:
    extends: .riviera_sim
    variables:
      extends: .vars
      PROJECT_NAME: MainBlocks/BA3_hps_csf_bp_inn
    # allow_failure: false

COMP:BA3_hps_csf_bp_inn:
  extends: .sim_comp
  variables:
    extends: .vars
    PROJECT_NAME: MainBlocks/BA3_hps_csf_bp_inn
    PROJECT_Q_NAME: MainBlocks/BA3_hps_csf_bp_inn_questa
    PROJECT_R_NAME: MainBlocks/BA3_hps_csf_bp_inn_riviera
  needs: ["SIM:BA3_hps_csf_bp_inn_questa","SIM:BA3_hps_csf_bp_inn_riviera"]

CHK:BA3_hps_csf_bp_inn:
  extends: .sim_check
  variables: 
    extends: .vars
    PROJECT_NAME: MainBlocks/BA3_hps_csf_bp_inn
    BLOCK: BA3_hps_csf_bp_inn
    SIMULATOR: questa
  needs: ["SIM:BA3_hps_csf_bp_inn_riviera"]
  artifacts:
    name: CHK_MainBlocks_BA3_hps_csf_bp_inn
    paths:
      - $CI_PROJECT_DIR/bin
    expire_in: 30 day
