#################### CocoTB Project ###########################
#Following libraries need to be installed in gitrunner for successful installation of pyenv and python 3.8.6
#sudo yum -y install zlib-devel
#sudo yum install openssl-devel
#sudo yum install libffi-devel
#sudo yum install bzip2-devel
#sudo yum install readline-devel
#sudo yum install sqlite-devel
#sudo yum install -y xz-devel Edited



GEN:cocotb:
    extends: .cocotb
    variables:
        extends: .vars
        PROJECT_NAME: MainBlocks/cocotb
    script: 

        - tb run test_config/config_mpl_mtc.json 2>&1 | tee cocotb_run.log
        # Make test fail if cocotb raised a failure
        - sh -c "! grep cocotb.result.TestFailure cocotb_run.log"
       
