cocotb_test:compile:
    extends: .cocotb_test
    stage: generation_and_simulation
    allow_failure: true
    interruptible: true
    variables:
        extends: .vars
        COCOTB_TEST: dummy
        PROJECT_NAME: tools/cocotb/

cocotb_test:test_lsf_inn:
    extends: .cocotb_test
    stage: user_post
    interruptible: true
    variables:
        extends: .vars
        COCOTB_TEST: lsf_inn
        PROJECT_NAME: tools/cocotb/

cocotb_test:test_lsf_mid:
    extends: .cocotb_test
    stage: user_post
    interruptible: true
    variables:
        extends: .vars
        COCOTB_TEST: lsf_mid
        PROJECT_NAME: tools/cocotb/

cocotb_test:test_lsf_out:
    extends: .cocotb_test
    stage: user_post
    interruptible: true
    variables:
        extends: .vars
        COCOTB_TEST: lsf_out
        PROJECT_NAME: tools/cocotb/

cocotb_test:test_mtc:
    extends: .cocotb_test
    stage: user_post
    interruptible: true
    variables:
        extends: .vars
        COCOTB_TEST: mtc
        PROJECT_NAME: tools/cocotb/


cocotb_test:test_ptcalc:
    extends: .cocotb_test
    stage: user_post
    interruptible: true
    variables:
        extends: .vars
        COCOTB_TEST: ptcalc
        PROJECT_NAME: tools/cocotb/



cocotb_test:test_ucm:
    extends: .cocotb_test
    stage: user_post
    interruptible: true
    variables:
        extends: .vars
        COCOTB_TEST: ucm
        PROJECT_NAME: tools/cocotb/


cocotb_test:test_ult_tar:
    extends: .cocotb_test
    stage: user_post
    interruptible: true
    variables:
        extends: .vars
        COCOTB_TEST: ult_tar
        PROJECT_NAME: tools/cocotb/


cocotb_test:test_hps_inn:
    extends: .cocotb_test
    stage: user_post
    interruptible: true
    variables:
        extends: .vars
        COCOTB_TEST: hps_inn
        PROJECT_NAME: tools/cocotb/








