#################### hps Project ###########################
GEN:hps:
    extends: .GEN
    variables:
      extends: .vars
      PROJECT_NAME: hps
      HOG_ONLY_SYNTH: 1 # if 1 runs only the synthesis

# SIM:hps:
#     extends: .SIM
#     variables:
#       extends: .vars
#       PROJECT_NAME: hps
