before_script:
    - export REPO=`echo $CI_PROJECT_URL | sed -e s#https://##`
    - git remote set-url origin https://${HOG_USER}:${HOG_PUSH_TOKEN}@$REPO
    - git config user.email ${HOG_EMAIL}
    - git config user.name ${HOG_USER}
    - git fetch origin $CI_COMMIT_REF_NAME
    - git fetch origin $CI_MERGE_REQUEST_TARGET_BRANCH_NAME
    - git checkout $CI_COMMIT_REF_NAME
    - git submodule init
    - git submodule update
    - ./Hog/Ignore_ip_xml.sh
    - export XILINXD_LICENSE_FILE=${HOG_XIL_LICENSE}
    - export PATH=$PATH:${HOG_PATH}
    - echo $HOG_PASSWORD | kinit $HOG_USER 
        || ( sleep 1 && echo $HOG_PASSWORD | kinit $HOG_USER ) 
        || ( sleep 1 && echo $HOG_PASSWORD | kinit $HOG_USER ) 
    - source ${PROFPGA_PATH}/bin/settings64.sh
