.tag-sr: &tag-sr
  tags:
     - docker



OpenMR:
    <<: *only-default
    only:
        refs:
            - schedules
    stage: merge
    script:
        - git pull
        - HOST=${CI_PROJECT_URL} CI_PROJECT_ID=${CI_PROJECT_ID} CI_COMMIT_REF_NAME=${CI_COMMIT_REF_NAME} GITLAB_USER_ID=${GITLAB_USER_ID}               PRIVATE_TOKEN=GXK25m5GX9Ysf5ySqz6J ./autoMergeRequest.sh       

