include:
    - project: 'hog/Hog'
      file: '/hog-dynamic.yml'
      ref: '102-unify-vivado-ci-stages'
  #   - local: '/.before_script.yml'
    - local: '/.devel_to_master.yml'
    - local: '/Top/csf/gitlab-ci.yml'
    # - local: '/Top/lsf/gitlab-ci.yml'
    - local: '/Top/tf/gitlab-ci.yml'
    #- local: '/Top/ucm/gitlab-ci.yml'
    #- local: '/Top/hp/gitlab-ci.yml'
    #- local: '/Top/heg/gitlab-ci.yml'
    #- local: '/Top/hps/gitlab-ci.yml'
    #- local: '/Top/hps_vp/gitlab-ci.yml'
    # - local: '/Top/ucm_hps/gitlab-ci.yml'
    #- local: '/Top/ult/gitlab-ci.yml'
    #- local: '/Top/ult_tp/gitlab-ci.yml'
    # - local: '/Top/hal/gitlab-ci.yml'
