#################### ull_ku15_b3a_ucm_mpl Project ###########################
GEN:ull_ku15_b3a_ucm_mpl:
    extends: .generate_project
    variables:
      extends: .vars
      PROJECT_NAME: ull_ku15_b3a_ucm_mpl
      HOG_ONLY_SYNTH: 1 # if 1 runs only the synthesis
      
    tags:
      - heavy-duty
      - hog

SIM:ull_ku15_b3a_ucm_mpl:
    extends: .simulate_project
    variables:
      extends: .vars
      PROJECT_NAME: ull_ku15_b3a_ucm_mpl
      HOG_CHECK_PROJVER: 0
    allow_failure: false
    tags:
      - questa
      - hog

# RIV:ull_ku15_b3a_ucm_mpl:
#     extends: .riviera_sim
#     variables:
#       extends: .riviera_vars
#       PROJECT_NAME: ull_ku15_b3a_ucm_mpl
#       HOG_CHECK_PROJVER: 0
#       HOG_PATH: "/opt/Xilinx/Vivado/2019.2/bin:/mnt/vd/Xilinx/Vivado/2019.2/bin:/afs/cern.ch/project/parc/riviera20214/bin/"
#       HOG_SIMULATION_LIB_PATH: "/home/l0mdtel/RivieraLib"
      
# CHK:ull_ku15_b3a_ucm_mpl:
#   extends: .sim_check
#   variables:
#     extends: .vars
#     PROJECT_NAME: ull_ku15_b3a_ucm_mpl
#   needs: ["SIM:ull_ku15_b3a_ucm_mpl","RIV:ull_ku15_b3a_ucm_mpl"]
  
# user_sim:ull_ku15_b3a_ucm_mpl:
#     extends: .user_sim
#     variables:
#       extends: .vars
#       PROJECT_NAME: ull_ku15_b3a_ucm_mpl
