#################### ull_ku15_b3a_ucm_mpl Project ###########################
generate_project:ull_ku15_b3a_ucm_mpl:
    extends: .generate_project
    variables:
      extends: .vars
      PROJECT_NAME: ull_ku15_b3a_ucm_mpl
      HOG_ONLY_SYNTH: 1 # if 1 runs only the synthesis

simulate_project:ull_ku15_b3a_ucm_mpl:
    extends: .simulate_project
    variables:
      extends: .vars
      PROJECT_NAME: ull_ku15_b3a_ucm_mpl
      HOG_CHECK_PROJVER: 0

# user_sim:ull_ku15_b3a_ucm_mpl:
#     extends: .user_sim
#     variables:
#       extends: .vars
#       PROJECT_NAME: ull_ku15_b3a_ucm_mpl
