#################### ult_tp_dev_xsim Project ###########################
generate_project:ult_tp_dev_xsim:
    extends: .generate_project
    variables:
      extends: .vars
      PROJECT_NAME: ult_tp_dev_xsim
      HOG_ONLY_SYNTH: 1 # if 1 runs only the synthesis

# user_sim:ult_tp_dev_xsim:
#     extends: .user_sim
#     variables:
#       extends: .vars
#       PROJECT_NAME: ult_tp_dev_xsim
#

simulate_project:ult_tp_dev_xsim:
    extends: .simulate_project
    variables:
      extends: .vars
      PROJECT_NAME: ult_tp_dev_xsim