#################### ptc_mpi Project ###########################
GEN:ptc_mpi:
    extends: .generate_project
    variables:
      extends: .vars
      PROJECT_NAME: MainBlocks/ptc_mpi
      HOG_NO_BITSTREAM: 1 # if 1 runs only the synthesis


SIM:ptc_mpi:
    extends: .simulate_project
    variables:
      extends: .vars
      PROJECT_NAME: MainBlocks/ptc_mpi
    tags:
      - questa
      - hog
      - "2020.2"
      
CHK:ptc_mpi:
  extends: .sim_check
  variables: 
    extends: .vars
    PROJECT_NAME: MainBlocks/ptc_mpi
    BLOCK: PTC
  needs: ["SIM:ptc_mpi"]
  artifacts:
    name: CHK_ptc
    paths:
      - $CI_PROJECT_DIR/bin
    expire_in: 30 day