--This file was auto-generated.
--Modifications might be lost.
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use work.AXIRegPkg.all;
use work.types.all;
use work.TAR_Ctrl.all;
use work.TAR_Ctrl_DEF.all;
entity TAR_interface is
  port (
    clk_axi          : in  std_logic;
    reset_axi_n      : in  std_logic;
    slave_readMOSI   : in  AXIReadMOSI;
    slave_readMISO   : out AXIReadMISO  := DefaultAXIReadMISO;
    slave_writeMOSI  : in  AXIWriteMOSI;
    slave_writeMISO  : out AXIWriteMISO := DefaultAXIWriteMISO;
    Mon              : in  TAR_Mon_t;
    Ctrl             : out TAR_Ctrl_t
    );
end entity TAR_interface;
architecture behavioral of TAR_interface is
  signal localAddress       : slv_32_t;
  signal localRdData        : slv_32_t;
  signal localRdData_latch  : slv_32_t;
  signal localWrData        : slv_32_t;
  signal localWrEn          : std_logic;
  signal localRdReq         : std_logic;
  signal localRdAck         : std_logic;


  signal reg_data :  slv32_array_t(integer range 0 to 873);
  constant Default_reg_data : slv32_array_t(integer range 0 to 873) := (others => x"00000000");
begin  -- architecture behavioral

  -------------------------------------------------------------------------------
  -- AXI 
  -------------------------------------------------------------------------------
  -------------------------------------------------------------------------------
  AXIRegBridge : entity work.axiLiteReg
    port map (
      clk_axi     => clk_axi,
      reset_axi_n => reset_axi_n,
      readMOSI    => slave_readMOSI,
      readMISO    => slave_readMISO,
      writeMOSI   => slave_writeMOSI,
      writeMISO   => slave_writeMISO,
      address     => localAddress,
      rd_data     => localRdData_latch,
      wr_data     => localWrData,
      write_en    => localWrEn,
      read_req    => localRdReq,
      read_ack    => localRdAck);

  latch_reads: process (clk_axi) is
  begin  -- process latch_reads
    if clk_axi'event and clk_axi = '1' then  -- rising clock edge
      if localRdReq = '1' then
        localRdData_latch <= localRdData;        
      end if;
    end if;
  end process latch_reads;
  reads: process (localRdReq,localAddress,reg_data) is
  begin  -- process reads
    localRdAck  <= '0';
    localRdData <= x"00000000";
    if localRdReq = '1' then
      localRdAck  <= '1';
      case to_integer(unsigned(localAddress(9 downto 0))) is

        when 1 => --0x1
          localRdData( 4)            <=  reg_data(1)( 4);                                        -- 
          localRdData( 5)            <=  reg_data(1)( 5);                                        -- 
          localRdData( 6)            <=  reg_data(1)( 6);                                        -- 
        when 2 => --0x2
          localRdData( 0)            <=  Mon.STATUS.ENABLED;                                     -- 
          localRdData( 1)            <=  Mon.STATUS.READY;                                       -- 
          localRdData( 2)            <=  Mon.STATUS.ERROR;                                       -- 
        when 529 => --0x211
          localRdData( 0)            <=  Mon.PL_STATION.PL_MID.PL_MEM(0).rd_rdy;                 -- Read ready
        when 530 => --0x212
          localRdData(11 downto  0)  <=  reg_data(530)(11 downto  0);                            -- wr_Address
          localRdData(27 downto 16)  <=  reg_data(530)(27 downto 16);                            -- rd_Address
        when 532 => --0x214
          localRdData(31 downto  0)  <=  reg_data(532)(31 downto  0);                            -- Write Data 0
        when 533 => --0x215
          localRdData( 9 downto  0)  <=  reg_data(533)( 9 downto  0);                            -- Write Data 1
        when 857 => --0x359
          localRdData( 9 downto  0)  <=  Mon.PL_STATION.PL_OUT.PL_MEM(4).rd_data.rd_data_1;      -- Read Data 1
        when 536 => --0x218
          localRdData(31 downto  0)  <=  Mon.PL_STATION.PL_MID.PL_MEM(0).rd_data.rd_data_0;      -- Read Data 0
        when 537 => --0x219
          localRdData( 9 downto  0)  <=  Mon.PL_STATION.PL_MID.PL_MEM(0).rd_data.rd_data_1;      -- Read Data 1
        when 545 => --0x221
          localRdData( 0)            <=  Mon.PL_STATION.PL_MID.PL_MEM(1).rd_rdy;                 -- Read ready
        when 546 => --0x222
          localRdData(11 downto  0)  <=  reg_data(546)(11 downto  0);                            -- wr_Address
          localRdData(27 downto 16)  <=  reg_data(546)(27 downto 16);                            -- rd_Address
        when 548 => --0x224
          localRdData(31 downto  0)  <=  reg_data(548)(31 downto  0);                            -- Write Data 0
        when 549 => --0x225
          localRdData( 9 downto  0)  <=  reg_data(549)( 9 downto  0);                            -- Write Data 1
        when 552 => --0x228
          localRdData(31 downto  0)  <=  Mon.PL_STATION.PL_MID.PL_MEM(1).rd_data.rd_data_0;      -- Read Data 0
        when 553 => --0x229
          localRdData( 9 downto  0)  <=  Mon.PL_STATION.PL_MID.PL_MEM(1).rd_data.rd_data_1;      -- Read Data 1
        when 561 => --0x231
          localRdData( 0)            <=  Mon.PL_STATION.PL_MID.PL_MEM(2).rd_rdy;                 -- Read ready
        when 562 => --0x232
          localRdData(11 downto  0)  <=  reg_data(562)(11 downto  0);                            -- wr_Address
          localRdData(27 downto 16)  <=  reg_data(562)(27 downto 16);                            -- rd_Address
        when 564 => --0x234
          localRdData(31 downto  0)  <=  reg_data(564)(31 downto  0);                            -- Write Data 0
        when 565 => --0x235
          localRdData( 9 downto  0)  <=  reg_data(565)( 9 downto  0);                            -- Write Data 1
        when 820 => --0x334
          localRdData(31 downto  0)  <=  reg_data(820)(31 downto  0);                            -- Write Data 0
        when 568 => --0x238
          localRdData(31 downto  0)  <=  Mon.PL_STATION.PL_MID.PL_MEM(2).rd_data.rd_data_0;      -- Read Data 0
        when 569 => --0x239
          localRdData( 9 downto  0)  <=  Mon.PL_STATION.PL_MID.PL_MEM(2).rd_data.rd_data_1;      -- Read Data 1
        when 577 => --0x241
          localRdData( 0)            <=  Mon.PL_STATION.PL_MID.PL_MEM(3).rd_rdy;                 -- Read ready
        when 578 => --0x242
          localRdData(11 downto  0)  <=  reg_data(578)(11 downto  0);                            -- wr_Address
          localRdData(27 downto 16)  <=  reg_data(578)(27 downto 16);                            -- rd_Address
        when 580 => --0x244
          localRdData(31 downto  0)  <=  reg_data(580)(31 downto  0);                            -- Write Data 0
        when 581 => --0x245
          localRdData( 9 downto  0)  <=  reg_data(581)( 9 downto  0);                            -- Write Data 1
        when 865 => --0x361
          localRdData( 0)            <=  Mon.PL_STATION.PL_OUT.PL_MEM(5).rd_rdy;                 -- Read ready
        when 584 => --0x248
          localRdData(31 downto  0)  <=  Mon.PL_STATION.PL_MID.PL_MEM(3).rd_data.rd_data_0;      -- Read Data 0
        when 585 => --0x249
          localRdData( 9 downto  0)  <=  Mon.PL_STATION.PL_MID.PL_MEM(3).rd_data.rd_data_1;      -- Read Data 1
        when 866 => --0x362
          localRdData(11 downto  0)  <=  reg_data(866)(11 downto  0);                            -- wr_Address
          localRdData(27 downto 16)  <=  reg_data(866)(27 downto 16);                            -- rd_Address
        when 593 => --0x251
          localRdData( 0)            <=  Mon.PL_STATION.PL_MID.PL_MEM(4).rd_rdy;                 -- Read ready
        when 594 => --0x252
          localRdData(11 downto  0)  <=  reg_data(594)(11 downto  0);                            -- wr_Address
          localRdData(27 downto 16)  <=  reg_data(594)(27 downto 16);                            -- rd_Address
        when 596 => --0x254
          localRdData(31 downto  0)  <=  reg_data(596)(31 downto  0);                            -- Write Data 0
        when 597 => --0x255
          localRdData( 9 downto  0)  <=  reg_data(597)( 9 downto  0);                            -- Write Data 1
        when 600 => --0x258
          localRdData(31 downto  0)  <=  Mon.PL_STATION.PL_MID.PL_MEM(4).rd_data.rd_data_0;      -- Read Data 0
        when 601 => --0x259
          localRdData( 9 downto  0)  <=  Mon.PL_STATION.PL_MID.PL_MEM(4).rd_data.rd_data_1;      -- Read Data 1
        when 869 => --0x365
          localRdData( 9 downto  0)  <=  reg_data(869)( 9 downto  0);                            -- Write Data 1
        when 609 => --0x261
          localRdData( 0)            <=  Mon.PL_STATION.PL_MID.PL_MEM(5).rd_rdy;                 -- Read ready
        when 610 => --0x262
          localRdData(11 downto  0)  <=  reg_data(610)(11 downto  0);                            -- wr_Address
          localRdData(27 downto 16)  <=  reg_data(610)(27 downto 16);                            -- rd_Address
        when 612 => --0x264
          localRdData(31 downto  0)  <=  reg_data(612)(31 downto  0);                            -- Write Data 0
        when 613 => --0x265
          localRdData( 9 downto  0)  <=  reg_data(613)( 9 downto  0);                            -- Write Data 1
        when 785 => --0x311
          localRdData( 0)            <=  Mon.PL_STATION.PL_OUT.PL_MEM(0).rd_rdy;                 -- Read ready
        when 616 => --0x268
          localRdData(31 downto  0)  <=  Mon.PL_STATION.PL_MID.PL_MEM(5).rd_data.rd_data_0;      -- Read Data 0
        when 617 => --0x269
          localRdData( 9 downto  0)  <=  Mon.PL_STATION.PL_MID.PL_MEM(5).rd_data.rd_data_1;      -- Read Data 1
        when 786 => --0x312
          localRdData(11 downto  0)  <=  reg_data(786)(11 downto  0);                            -- wr_Address
          localRdData(27 downto 16)  <=  reg_data(786)(27 downto 16);                            -- rd_Address
        when 856 => --0x358
          localRdData(31 downto  0)  <=  Mon.PL_STATION.PL_OUT.PL_MEM(4).rd_data.rd_data_0;      -- Read Data 0
        when 872 => --0x368
          localRdData(31 downto  0)  <=  Mon.PL_STATION.PL_OUT.PL_MEM(5).rd_data.rd_data_0;      -- Read Data 0
        when 873 => --0x369
          localRdData( 9 downto  0)  <=  Mon.PL_STATION.PL_OUT.PL_MEM(5).rd_data.rd_data_1;      -- Read Data 1
        when 788 => --0x314
          localRdData(31 downto  0)  <=  reg_data(788)(31 downto  0);                            -- Write Data 0
        when 789 => --0x315
          localRdData( 9 downto  0)  <=  reg_data(789)( 9 downto  0);                            -- Write Data 1
        when 792 => --0x318
          localRdData(31 downto  0)  <=  Mon.PL_STATION.PL_OUT.PL_MEM(0).rd_data.rd_data_0;      -- Read Data 0
        when 281 => --0x119
          localRdData( 9 downto  0)  <=  Mon.PL_STATION.PL_INN.PL_MEM(0).rd_data.rd_data_1;      -- Read Data 1
        when 824 => --0x338
          localRdData(31 downto  0)  <=  Mon.PL_STATION.PL_OUT.PL_MEM(2).rd_data.rd_data_0;      -- Read Data 0
        when 801 => --0x321
          localRdData( 0)            <=  Mon.PL_STATION.PL_OUT.PL_MEM(1).rd_rdy;                 -- Read ready
        when 290 => --0x122
          localRdData(11 downto  0)  <=  reg_data(290)(11 downto  0);                            -- wr_Address
          localRdData(27 downto 16)  <=  reg_data(290)(27 downto 16);                            -- rd_Address
        when 292 => --0x124
          localRdData(31 downto  0)  <=  reg_data(292)(31 downto  0);                            -- Write Data 0
        when 805 => --0x325
          localRdData( 9 downto  0)  <=  reg_data(805)( 9 downto  0);                            -- Write Data 1
        when 808 => --0x328
          localRdData(31 downto  0)  <=  Mon.PL_STATION.PL_OUT.PL_MEM(1).rd_data.rd_data_0;      -- Read Data 0
        when 809 => --0x329
          localRdData( 9 downto  0)  <=  Mon.PL_STATION.PL_OUT.PL_MEM(1).rd_data.rd_data_1;      -- Read Data 1
        when 273 => --0x111
          localRdData( 0)            <=  Mon.PL_STATION.PL_INN.PL_MEM(0).rd_rdy;                 -- Read ready
        when 274 => --0x112
          localRdData(11 downto  0)  <=  reg_data(274)(11 downto  0);                            -- wr_Address
          localRdData(27 downto 16)  <=  reg_data(274)(27 downto 16);                            -- rd_Address
        when 276 => --0x114
          localRdData(31 downto  0)  <=  reg_data(276)(31 downto  0);                            -- Write Data 0
        when 277 => --0x115
          localRdData( 9 downto  0)  <=  reg_data(277)( 9 downto  0);                            -- Write Data 1
        when 280 => --0x118
          localRdData(31 downto  0)  <=  Mon.PL_STATION.PL_INN.PL_MEM(0).rd_data.rd_data_0;      -- Read Data 0
        when 793 => --0x319
          localRdData( 9 downto  0)  <=  Mon.PL_STATION.PL_OUT.PL_MEM(0).rd_data.rd_data_1;      -- Read Data 1
        when 289 => --0x121
          localRdData( 0)            <=  Mon.PL_STATION.PL_INN.PL_MEM(1).rd_rdy;                 -- Read ready
        when 802 => --0x322
          localRdData(11 downto  0)  <=  reg_data(802)(11 downto  0);                            -- wr_Address
          localRdData(27 downto 16)  <=  reg_data(802)(27 downto 16);                            -- rd_Address
        when 804 => --0x324
          localRdData(31 downto  0)  <=  reg_data(804)(31 downto  0);                            -- Write Data 0
        when 293 => --0x125
          localRdData( 9 downto  0)  <=  reg_data(293)( 9 downto  0);                            -- Write Data 1
        when 817 => --0x331
          localRdData( 0)            <=  Mon.PL_STATION.PL_OUT.PL_MEM(2).rd_rdy;                 -- Read ready
        when 296 => --0x128
          localRdData(31 downto  0)  <=  Mon.PL_STATION.PL_INN.PL_MEM(1).rd_data.rd_data_0;      -- Read Data 0
        when 297 => --0x129
          localRdData( 9 downto  0)  <=  Mon.PL_STATION.PL_INN.PL_MEM(1).rd_data.rd_data_1;      -- Read Data 1
        when 818 => --0x332
          localRdData(11 downto  0)  <=  reg_data(818)(11 downto  0);                            -- wr_Address
          localRdData(27 downto 16)  <=  reg_data(818)(27 downto 16);                            -- rd_Address
        when 305 => --0x131
          localRdData( 0)            <=  Mon.PL_STATION.PL_INN.PL_MEM(2).rd_rdy;                 -- Read ready
        when 306 => --0x132
          localRdData(11 downto  0)  <=  reg_data(306)(11 downto  0);                            -- wr_Address
          localRdData(27 downto 16)  <=  reg_data(306)(27 downto 16);                            -- rd_Address
        when 308 => --0x134
          localRdData(31 downto  0)  <=  reg_data(308)(31 downto  0);                            -- Write Data 0
        when 309 => --0x135
          localRdData( 9 downto  0)  <=  reg_data(309)( 9 downto  0);                            -- Write Data 1
        when 312 => --0x138
          localRdData(31 downto  0)  <=  Mon.PL_STATION.PL_INN.PL_MEM(2).rd_data.rd_data_0;      -- Read Data 0
        when 313 => --0x139
          localRdData( 9 downto  0)  <=  Mon.PL_STATION.PL_INN.PL_MEM(2).rd_data.rd_data_1;      -- Read Data 1
        when 821 => --0x335
          localRdData( 9 downto  0)  <=  reg_data(821)( 9 downto  0);                            -- Write Data 1
        when 321 => --0x141
          localRdData( 0)            <=  Mon.PL_STATION.PL_INN.PL_MEM(3).rd_rdy;                 -- Read ready
        when 322 => --0x142
          localRdData(11 downto  0)  <=  reg_data(322)(11 downto  0);                            -- wr_Address
          localRdData(27 downto 16)  <=  reg_data(322)(27 downto 16);                            -- rd_Address
        when 324 => --0x144
          localRdData(31 downto  0)  <=  reg_data(324)(31 downto  0);                            -- Write Data 0
        when 325 => --0x145
          localRdData( 9 downto  0)  <=  reg_data(325)( 9 downto  0);                            -- Write Data 1
        when 328 => --0x148
          localRdData(31 downto  0)  <=  Mon.PL_STATION.PL_INN.PL_MEM(3).rd_data.rd_data_0;      -- Read Data 0
        when 329 => --0x149
          localRdData( 9 downto  0)  <=  Mon.PL_STATION.PL_INN.PL_MEM(3).rd_data.rd_data_1;      -- Read Data 1
        when 337 => --0x151
          localRdData( 0)            <=  Mon.PL_STATION.PL_INN.PL_MEM(4).rd_rdy;                 -- Read ready
        when 338 => --0x152
          localRdData(11 downto  0)  <=  reg_data(338)(11 downto  0);                            -- wr_Address
          localRdData(27 downto 16)  <=  reg_data(338)(27 downto 16);                            -- rd_Address
        when 340 => --0x154
          localRdData(31 downto  0)  <=  reg_data(340)(31 downto  0);                            -- Write Data 0
        when 341 => --0x155
          localRdData( 9 downto  0)  <=  reg_data(341)( 9 downto  0);                            -- Write Data 1
        when 825 => --0x339
          localRdData( 9 downto  0)  <=  Mon.PL_STATION.PL_OUT.PL_MEM(2).rd_data.rd_data_1;      -- Read Data 1
        when 344 => --0x158
          localRdData(31 downto  0)  <=  Mon.PL_STATION.PL_INN.PL_MEM(4).rd_data.rd_data_0;      -- Read Data 0
        when 345 => --0x159
          localRdData( 9 downto  0)  <=  Mon.PL_STATION.PL_INN.PL_MEM(4).rd_data.rd_data_1;      -- Read Data 1
        when 353 => --0x161
          localRdData( 0)            <=  Mon.PL_STATION.PL_INN.PL_MEM(5).rd_rdy;                 -- Read ready
        when 354 => --0x162
          localRdData(11 downto  0)  <=  reg_data(354)(11 downto  0);                            -- wr_Address
          localRdData(27 downto 16)  <=  reg_data(354)(27 downto 16);                            -- rd_Address
        when 356 => --0x164
          localRdData(31 downto  0)  <=  reg_data(356)(31 downto  0);                            -- Write Data 0
        when 357 => --0x165
          localRdData( 9 downto  0)  <=  reg_data(357)( 9 downto  0);                            -- Write Data 1
        when 360 => --0x168
          localRdData(31 downto  0)  <=  Mon.PL_STATION.PL_INN.PL_MEM(5).rd_data.rd_data_0;      -- Read Data 0
        when 361 => --0x169
          localRdData( 9 downto  0)  <=  Mon.PL_STATION.PL_INN.PL_MEM(5).rd_data.rd_data_1;      -- Read Data 1
        when 833 => --0x341
          localRdData( 0)            <=  Mon.PL_STATION.PL_OUT.PL_MEM(3).rd_rdy;                 -- Read ready
        when 834 => --0x342
          localRdData(11 downto  0)  <=  reg_data(834)(11 downto  0);                            -- wr_Address
          localRdData(27 downto 16)  <=  reg_data(834)(27 downto 16);                            -- rd_Address
        when 836 => --0x344
          localRdData(31 downto  0)  <=  reg_data(836)(31 downto  0);                            -- Write Data 0
        when 837 => --0x345
          localRdData( 9 downto  0)  <=  reg_data(837)( 9 downto  0);                            -- Write Data 1
        when 840 => --0x348
          localRdData(31 downto  0)  <=  Mon.PL_STATION.PL_OUT.PL_MEM(3).rd_data.rd_data_0;      -- Read Data 0
        when 841 => --0x349
          localRdData( 9 downto  0)  <=  Mon.PL_STATION.PL_OUT.PL_MEM(3).rd_data.rd_data_1;      -- Read Data 1
        when 868 => --0x364
          localRdData(31 downto  0)  <=  reg_data(868)(31 downto  0);                            -- Write Data 0
        when 849 => --0x351
          localRdData( 0)            <=  Mon.PL_STATION.PL_OUT.PL_MEM(4).rd_rdy;                 -- Read ready
        when 850 => --0x352
          localRdData(11 downto  0)  <=  reg_data(850)(11 downto  0);                            -- wr_Address
          localRdData(27 downto 16)  <=  reg_data(850)(27 downto 16);                            -- rd_Address
        when 852 => --0x354
          localRdData(31 downto  0)  <=  reg_data(852)(31 downto  0);                            -- Write Data 0
        when 853 => --0x355
          localRdData( 9 downto  0)  <=  reg_data(853)( 9 downto  0);                            -- Write Data 1


        when others =>
          localRdData <= x"00000000";
      end case;
    end if;
  end process reads;




  -- Register mapping to ctrl structures
  Ctrl.CONFIGS.INPUT_EN                               <=  reg_data(1)( 4);                 
  Ctrl.CONFIGS.OUTPUT_EN                              <=  reg_data(1)( 5);                 
  Ctrl.CONFIGS.FLUSH_MEM_RESET                        <=  reg_data(1)( 6);                 
  Ctrl.PL_STATION.PL_INN.PL_MEM(0).wr_addr            <=  reg_data(274)(11 downto  0);     
  Ctrl.PL_STATION.PL_INN.PL_MEM(0).rd_addr            <=  reg_data(274)(27 downto 16);     
  Ctrl.PL_STATION.PL_INN.PL_MEM(0).wr_data.wr_data_0  <=  reg_data(276)(31 downto  0);     
  Ctrl.PL_STATION.PL_INN.PL_MEM(0).wr_data.wr_data_1  <=  reg_data(277)( 9 downto  0);     
  Ctrl.PL_STATION.PL_INN.PL_MEM(1).wr_addr            <=  reg_data(290)(11 downto  0);     
  Ctrl.PL_STATION.PL_INN.PL_MEM(1).rd_addr            <=  reg_data(290)(27 downto 16);     
  Ctrl.PL_STATION.PL_INN.PL_MEM(1).wr_data.wr_data_0  <=  reg_data(292)(31 downto  0);     
  Ctrl.PL_STATION.PL_INN.PL_MEM(1).wr_data.wr_data_1  <=  reg_data(293)( 9 downto  0);     
  Ctrl.PL_STATION.PL_INN.PL_MEM(2).wr_addr            <=  reg_data(306)(11 downto  0);     
  Ctrl.PL_STATION.PL_INN.PL_MEM(2).rd_addr            <=  reg_data(306)(27 downto 16);     
  Ctrl.PL_STATION.PL_INN.PL_MEM(2).wr_data.wr_data_0  <=  reg_data(308)(31 downto  0);     
  Ctrl.PL_STATION.PL_INN.PL_MEM(2).wr_data.wr_data_1  <=  reg_data(309)( 9 downto  0);     
  Ctrl.PL_STATION.PL_INN.PL_MEM(3).wr_addr            <=  reg_data(322)(11 downto  0);     
  Ctrl.PL_STATION.PL_INN.PL_MEM(3).rd_addr            <=  reg_data(322)(27 downto 16);     
  Ctrl.PL_STATION.PL_INN.PL_MEM(3).wr_data.wr_data_0  <=  reg_data(324)(31 downto  0);     
  Ctrl.PL_STATION.PL_INN.PL_MEM(3).wr_data.wr_data_1  <=  reg_data(325)( 9 downto  0);     
  Ctrl.PL_STATION.PL_INN.PL_MEM(4).wr_addr            <=  reg_data(338)(11 downto  0);     
  Ctrl.PL_STATION.PL_INN.PL_MEM(4).rd_addr            <=  reg_data(338)(27 downto 16);     
  Ctrl.PL_STATION.PL_INN.PL_MEM(4).wr_data.wr_data_0  <=  reg_data(340)(31 downto  0);     
  Ctrl.PL_STATION.PL_INN.PL_MEM(4).wr_data.wr_data_1  <=  reg_data(341)( 9 downto  0);     
  Ctrl.PL_STATION.PL_INN.PL_MEM(5).wr_addr            <=  reg_data(354)(11 downto  0);     
  Ctrl.PL_STATION.PL_INN.PL_MEM(5).rd_addr            <=  reg_data(354)(27 downto 16);     
  Ctrl.PL_STATION.PL_INN.PL_MEM(5).wr_data.wr_data_0  <=  reg_data(356)(31 downto  0);     
  Ctrl.PL_STATION.PL_INN.PL_MEM(5).wr_data.wr_data_1  <=  reg_data(357)( 9 downto  0);     
  Ctrl.PL_STATION.PL_MID.PL_MEM(0).wr_addr            <=  reg_data(530)(11 downto  0);     
  Ctrl.PL_STATION.PL_MID.PL_MEM(0).rd_addr            <=  reg_data(530)(27 downto 16);     
  Ctrl.PL_STATION.PL_MID.PL_MEM(0).wr_data.wr_data_0  <=  reg_data(532)(31 downto  0);     
  Ctrl.PL_STATION.PL_MID.PL_MEM(0).wr_data.wr_data_1  <=  reg_data(533)( 9 downto  0);     
  Ctrl.PL_STATION.PL_MID.PL_MEM(1).wr_addr            <=  reg_data(546)(11 downto  0);     
  Ctrl.PL_STATION.PL_MID.PL_MEM(1).rd_addr            <=  reg_data(546)(27 downto 16);     
  Ctrl.PL_STATION.PL_MID.PL_MEM(1).wr_data.wr_data_0  <=  reg_data(548)(31 downto  0);     
  Ctrl.PL_STATION.PL_MID.PL_MEM(1).wr_data.wr_data_1  <=  reg_data(549)( 9 downto  0);     
  Ctrl.PL_STATION.PL_MID.PL_MEM(2).wr_addr            <=  reg_data(562)(11 downto  0);     
  Ctrl.PL_STATION.PL_MID.PL_MEM(2).rd_addr            <=  reg_data(562)(27 downto 16);     
  Ctrl.PL_STATION.PL_MID.PL_MEM(2).wr_data.wr_data_0  <=  reg_data(564)(31 downto  0);     
  Ctrl.PL_STATION.PL_MID.PL_MEM(2).wr_data.wr_data_1  <=  reg_data(565)( 9 downto  0);     
  Ctrl.PL_STATION.PL_MID.PL_MEM(3).wr_addr            <=  reg_data(578)(11 downto  0);     
  Ctrl.PL_STATION.PL_MID.PL_MEM(3).rd_addr            <=  reg_data(578)(27 downto 16);     
  Ctrl.PL_STATION.PL_MID.PL_MEM(3).wr_data.wr_data_0  <=  reg_data(580)(31 downto  0);     
  Ctrl.PL_STATION.PL_MID.PL_MEM(3).wr_data.wr_data_1  <=  reg_data(581)( 9 downto  0);     
  Ctrl.PL_STATION.PL_MID.PL_MEM(4).wr_addr            <=  reg_data(594)(11 downto  0);     
  Ctrl.PL_STATION.PL_MID.PL_MEM(4).rd_addr            <=  reg_data(594)(27 downto 16);     
  Ctrl.PL_STATION.PL_MID.PL_MEM(4).wr_data.wr_data_0  <=  reg_data(596)(31 downto  0);     
  Ctrl.PL_STATION.PL_MID.PL_MEM(4).wr_data.wr_data_1  <=  reg_data(597)( 9 downto  0);     
  Ctrl.PL_STATION.PL_MID.PL_MEM(5).wr_addr            <=  reg_data(610)(11 downto  0);     
  Ctrl.PL_STATION.PL_MID.PL_MEM(5).rd_addr            <=  reg_data(610)(27 downto 16);     
  Ctrl.PL_STATION.PL_MID.PL_MEM(5).wr_data.wr_data_0  <=  reg_data(612)(31 downto  0);     
  Ctrl.PL_STATION.PL_MID.PL_MEM(5).wr_data.wr_data_1  <=  reg_data(613)( 9 downto  0);     
  Ctrl.PL_STATION.PL_OUT.PL_MEM(0).wr_addr            <=  reg_data(786)(11 downto  0);     
  Ctrl.PL_STATION.PL_OUT.PL_MEM(0).rd_addr            <=  reg_data(786)(27 downto 16);     
  Ctrl.PL_STATION.PL_OUT.PL_MEM(0).wr_data.wr_data_0  <=  reg_data(788)(31 downto  0);     
  Ctrl.PL_STATION.PL_OUT.PL_MEM(0).wr_data.wr_data_1  <=  reg_data(789)( 9 downto  0);     
  Ctrl.PL_STATION.PL_OUT.PL_MEM(1).wr_addr            <=  reg_data(802)(11 downto  0);     
  Ctrl.PL_STATION.PL_OUT.PL_MEM(1).rd_addr            <=  reg_data(802)(27 downto 16);     
  Ctrl.PL_STATION.PL_OUT.PL_MEM(1).wr_data.wr_data_0  <=  reg_data(804)(31 downto  0);     
  Ctrl.PL_STATION.PL_OUT.PL_MEM(1).wr_data.wr_data_1  <=  reg_data(805)( 9 downto  0);     
  Ctrl.PL_STATION.PL_OUT.PL_MEM(2).wr_addr            <=  reg_data(818)(11 downto  0);     
  Ctrl.PL_STATION.PL_OUT.PL_MEM(2).rd_addr            <=  reg_data(818)(27 downto 16);     
  Ctrl.PL_STATION.PL_OUT.PL_MEM(2).wr_data.wr_data_0  <=  reg_data(820)(31 downto  0);     
  Ctrl.PL_STATION.PL_OUT.PL_MEM(2).wr_data.wr_data_1  <=  reg_data(821)( 9 downto  0);     
  Ctrl.PL_STATION.PL_OUT.PL_MEM(3).wr_addr            <=  reg_data(834)(11 downto  0);     
  Ctrl.PL_STATION.PL_OUT.PL_MEM(3).rd_addr            <=  reg_data(834)(27 downto 16);     
  Ctrl.PL_STATION.PL_OUT.PL_MEM(3).wr_data.wr_data_0  <=  reg_data(836)(31 downto  0);     
  Ctrl.PL_STATION.PL_OUT.PL_MEM(3).wr_data.wr_data_1  <=  reg_data(837)( 9 downto  0);     
  Ctrl.PL_STATION.PL_OUT.PL_MEM(4).wr_addr            <=  reg_data(850)(11 downto  0);     
  Ctrl.PL_STATION.PL_OUT.PL_MEM(4).rd_addr            <=  reg_data(850)(27 downto 16);     
  Ctrl.PL_STATION.PL_OUT.PL_MEM(4).wr_data.wr_data_0  <=  reg_data(852)(31 downto  0);     
  Ctrl.PL_STATION.PL_OUT.PL_MEM(4).wr_data.wr_data_1  <=  reg_data(853)( 9 downto  0);     
  Ctrl.PL_STATION.PL_OUT.PL_MEM(5).wr_addr            <=  reg_data(866)(11 downto  0);     
  Ctrl.PL_STATION.PL_OUT.PL_MEM(5).rd_addr            <=  reg_data(866)(27 downto 16);     
  Ctrl.PL_STATION.PL_OUT.PL_MEM(5).wr_data.wr_data_0  <=  reg_data(868)(31 downto  0);     
  Ctrl.PL_STATION.PL_OUT.PL_MEM(5).wr_data.wr_data_1  <=  reg_data(869)( 9 downto  0);     


  reg_writes: process (clk_axi, reset_axi_n) is
  begin  -- process reg_writes
    if reset_axi_n = '0' then                 -- asynchronous reset (active low)
      reg_data(1)( 4)  <= DEFAULT_TAR_CTRL_t.CONFIGS.INPUT_EN;
      reg_data(1)( 5)  <= DEFAULT_TAR_CTRL_t.CONFIGS.OUTPUT_EN;
      reg_data(1)( 6)  <= DEFAULT_TAR_CTRL_t.CONFIGS.FLUSH_MEM_RESET;
      reg_data(274)(11 downto  0)  <= DEFAULT_TAR_CTRL_t.PL_STATION.PL_INN.PL_MEM(0).wr_addr;
      reg_data(274)(27 downto 16)  <= DEFAULT_TAR_CTRL_t.PL_STATION.PL_INN.PL_MEM(0).rd_addr;
      reg_data(276)(31 downto  0)  <= DEFAULT_TAR_CTRL_t.PL_STATION.PL_INN.PL_MEM(0).wr_data.wr_data_0;
      reg_data(277)( 9 downto  0)  <= DEFAULT_TAR_CTRL_t.PL_STATION.PL_INN.PL_MEM(0).wr_data.wr_data_1;
      reg_data(290)(11 downto  0)  <= DEFAULT_TAR_CTRL_t.PL_STATION.PL_INN.PL_MEM(1).wr_addr;
      reg_data(290)(27 downto 16)  <= DEFAULT_TAR_CTRL_t.PL_STATION.PL_INN.PL_MEM(1).rd_addr;
      reg_data(292)(31 downto  0)  <= DEFAULT_TAR_CTRL_t.PL_STATION.PL_INN.PL_MEM(1).wr_data.wr_data_0;
      reg_data(293)( 9 downto  0)  <= DEFAULT_TAR_CTRL_t.PL_STATION.PL_INN.PL_MEM(1).wr_data.wr_data_1;
      reg_data(306)(11 downto  0)  <= DEFAULT_TAR_CTRL_t.PL_STATION.PL_INN.PL_MEM(2).wr_addr;
      reg_data(306)(27 downto 16)  <= DEFAULT_TAR_CTRL_t.PL_STATION.PL_INN.PL_MEM(2).rd_addr;
      reg_data(308)(31 downto  0)  <= DEFAULT_TAR_CTRL_t.PL_STATION.PL_INN.PL_MEM(2).wr_data.wr_data_0;
      reg_data(309)( 9 downto  0)  <= DEFAULT_TAR_CTRL_t.PL_STATION.PL_INN.PL_MEM(2).wr_data.wr_data_1;
      reg_data(322)(11 downto  0)  <= DEFAULT_TAR_CTRL_t.PL_STATION.PL_INN.PL_MEM(3).wr_addr;
      reg_data(322)(27 downto 16)  <= DEFAULT_TAR_CTRL_t.PL_STATION.PL_INN.PL_MEM(3).rd_addr;
      reg_data(324)(31 downto  0)  <= DEFAULT_TAR_CTRL_t.PL_STATION.PL_INN.PL_MEM(3).wr_data.wr_data_0;
      reg_data(325)( 9 downto  0)  <= DEFAULT_TAR_CTRL_t.PL_STATION.PL_INN.PL_MEM(3).wr_data.wr_data_1;
      reg_data(338)(11 downto  0)  <= DEFAULT_TAR_CTRL_t.PL_STATION.PL_INN.PL_MEM(4).wr_addr;
      reg_data(338)(27 downto 16)  <= DEFAULT_TAR_CTRL_t.PL_STATION.PL_INN.PL_MEM(4).rd_addr;
      reg_data(340)(31 downto  0)  <= DEFAULT_TAR_CTRL_t.PL_STATION.PL_INN.PL_MEM(4).wr_data.wr_data_0;
      reg_data(341)( 9 downto  0)  <= DEFAULT_TAR_CTRL_t.PL_STATION.PL_INN.PL_MEM(4).wr_data.wr_data_1;
      reg_data(354)(11 downto  0)  <= DEFAULT_TAR_CTRL_t.PL_STATION.PL_INN.PL_MEM(5).wr_addr;
      reg_data(354)(27 downto 16)  <= DEFAULT_TAR_CTRL_t.PL_STATION.PL_INN.PL_MEM(5).rd_addr;
      reg_data(356)(31 downto  0)  <= DEFAULT_TAR_CTRL_t.PL_STATION.PL_INN.PL_MEM(5).wr_data.wr_data_0;
      reg_data(357)( 9 downto  0)  <= DEFAULT_TAR_CTRL_t.PL_STATION.PL_INN.PL_MEM(5).wr_data.wr_data_1;
      reg_data(530)(11 downto  0)  <= DEFAULT_TAR_CTRL_t.PL_STATION.PL_MID.PL_MEM(0).wr_addr;
      reg_data(530)(27 downto 16)  <= DEFAULT_TAR_CTRL_t.PL_STATION.PL_MID.PL_MEM(0).rd_addr;
      reg_data(532)(31 downto  0)  <= DEFAULT_TAR_CTRL_t.PL_STATION.PL_MID.PL_MEM(0).wr_data.wr_data_0;
      reg_data(533)( 9 downto  0)  <= DEFAULT_TAR_CTRL_t.PL_STATION.PL_MID.PL_MEM(0).wr_data.wr_data_1;
      reg_data(546)(11 downto  0)  <= DEFAULT_TAR_CTRL_t.PL_STATION.PL_MID.PL_MEM(1).wr_addr;
      reg_data(546)(27 downto 16)  <= DEFAULT_TAR_CTRL_t.PL_STATION.PL_MID.PL_MEM(1).rd_addr;
      reg_data(548)(31 downto  0)  <= DEFAULT_TAR_CTRL_t.PL_STATION.PL_MID.PL_MEM(1).wr_data.wr_data_0;
      reg_data(549)( 9 downto  0)  <= DEFAULT_TAR_CTRL_t.PL_STATION.PL_MID.PL_MEM(1).wr_data.wr_data_1;
      reg_data(562)(11 downto  0)  <= DEFAULT_TAR_CTRL_t.PL_STATION.PL_MID.PL_MEM(2).wr_addr;
      reg_data(562)(27 downto 16)  <= DEFAULT_TAR_CTRL_t.PL_STATION.PL_MID.PL_MEM(2).rd_addr;
      reg_data(564)(31 downto  0)  <= DEFAULT_TAR_CTRL_t.PL_STATION.PL_MID.PL_MEM(2).wr_data.wr_data_0;
      reg_data(565)( 9 downto  0)  <= DEFAULT_TAR_CTRL_t.PL_STATION.PL_MID.PL_MEM(2).wr_data.wr_data_1;
      reg_data(578)(11 downto  0)  <= DEFAULT_TAR_CTRL_t.PL_STATION.PL_MID.PL_MEM(3).wr_addr;
      reg_data(578)(27 downto 16)  <= DEFAULT_TAR_CTRL_t.PL_STATION.PL_MID.PL_MEM(3).rd_addr;
      reg_data(580)(31 downto  0)  <= DEFAULT_TAR_CTRL_t.PL_STATION.PL_MID.PL_MEM(3).wr_data.wr_data_0;
      reg_data(581)( 9 downto  0)  <= DEFAULT_TAR_CTRL_t.PL_STATION.PL_MID.PL_MEM(3).wr_data.wr_data_1;
      reg_data(594)(11 downto  0)  <= DEFAULT_TAR_CTRL_t.PL_STATION.PL_MID.PL_MEM(4).wr_addr;
      reg_data(594)(27 downto 16)  <= DEFAULT_TAR_CTRL_t.PL_STATION.PL_MID.PL_MEM(4).rd_addr;
      reg_data(596)(31 downto  0)  <= DEFAULT_TAR_CTRL_t.PL_STATION.PL_MID.PL_MEM(4).wr_data.wr_data_0;
      reg_data(597)( 9 downto  0)  <= DEFAULT_TAR_CTRL_t.PL_STATION.PL_MID.PL_MEM(4).wr_data.wr_data_1;
      reg_data(610)(11 downto  0)  <= DEFAULT_TAR_CTRL_t.PL_STATION.PL_MID.PL_MEM(5).wr_addr;
      reg_data(610)(27 downto 16)  <= DEFAULT_TAR_CTRL_t.PL_STATION.PL_MID.PL_MEM(5).rd_addr;
      reg_data(612)(31 downto  0)  <= DEFAULT_TAR_CTRL_t.PL_STATION.PL_MID.PL_MEM(5).wr_data.wr_data_0;
      reg_data(613)( 9 downto  0)  <= DEFAULT_TAR_CTRL_t.PL_STATION.PL_MID.PL_MEM(5).wr_data.wr_data_1;
      reg_data(786)(11 downto  0)  <= DEFAULT_TAR_CTRL_t.PL_STATION.PL_OUT.PL_MEM(0).wr_addr;
      reg_data(786)(27 downto 16)  <= DEFAULT_TAR_CTRL_t.PL_STATION.PL_OUT.PL_MEM(0).rd_addr;
      reg_data(788)(31 downto  0)  <= DEFAULT_TAR_CTRL_t.PL_STATION.PL_OUT.PL_MEM(0).wr_data.wr_data_0;
      reg_data(789)( 9 downto  0)  <= DEFAULT_TAR_CTRL_t.PL_STATION.PL_OUT.PL_MEM(0).wr_data.wr_data_1;
      reg_data(802)(11 downto  0)  <= DEFAULT_TAR_CTRL_t.PL_STATION.PL_OUT.PL_MEM(1).wr_addr;
      reg_data(802)(27 downto 16)  <= DEFAULT_TAR_CTRL_t.PL_STATION.PL_OUT.PL_MEM(1).rd_addr;
      reg_data(804)(31 downto  0)  <= DEFAULT_TAR_CTRL_t.PL_STATION.PL_OUT.PL_MEM(1).wr_data.wr_data_0;
      reg_data(805)( 9 downto  0)  <= DEFAULT_TAR_CTRL_t.PL_STATION.PL_OUT.PL_MEM(1).wr_data.wr_data_1;
      reg_data(818)(11 downto  0)  <= DEFAULT_TAR_CTRL_t.PL_STATION.PL_OUT.PL_MEM(2).wr_addr;
      reg_data(818)(27 downto 16)  <= DEFAULT_TAR_CTRL_t.PL_STATION.PL_OUT.PL_MEM(2).rd_addr;
      reg_data(820)(31 downto  0)  <= DEFAULT_TAR_CTRL_t.PL_STATION.PL_OUT.PL_MEM(2).wr_data.wr_data_0;
      reg_data(821)( 9 downto  0)  <= DEFAULT_TAR_CTRL_t.PL_STATION.PL_OUT.PL_MEM(2).wr_data.wr_data_1;
      reg_data(834)(11 downto  0)  <= DEFAULT_TAR_CTRL_t.PL_STATION.PL_OUT.PL_MEM(3).wr_addr;
      reg_data(834)(27 downto 16)  <= DEFAULT_TAR_CTRL_t.PL_STATION.PL_OUT.PL_MEM(3).rd_addr;
      reg_data(836)(31 downto  0)  <= DEFAULT_TAR_CTRL_t.PL_STATION.PL_OUT.PL_MEM(3).wr_data.wr_data_0;
      reg_data(837)( 9 downto  0)  <= DEFAULT_TAR_CTRL_t.PL_STATION.PL_OUT.PL_MEM(3).wr_data.wr_data_1;
      reg_data(850)(11 downto  0)  <= DEFAULT_TAR_CTRL_t.PL_STATION.PL_OUT.PL_MEM(4).wr_addr;
      reg_data(850)(27 downto 16)  <= DEFAULT_TAR_CTRL_t.PL_STATION.PL_OUT.PL_MEM(4).rd_addr;
      reg_data(852)(31 downto  0)  <= DEFAULT_TAR_CTRL_t.PL_STATION.PL_OUT.PL_MEM(4).wr_data.wr_data_0;
      reg_data(853)( 9 downto  0)  <= DEFAULT_TAR_CTRL_t.PL_STATION.PL_OUT.PL_MEM(4).wr_data.wr_data_1;
      reg_data(866)(11 downto  0)  <= DEFAULT_TAR_CTRL_t.PL_STATION.PL_OUT.PL_MEM(5).wr_addr;
      reg_data(866)(27 downto 16)  <= DEFAULT_TAR_CTRL_t.PL_STATION.PL_OUT.PL_MEM(5).rd_addr;
      reg_data(868)(31 downto  0)  <= DEFAULT_TAR_CTRL_t.PL_STATION.PL_OUT.PL_MEM(5).wr_data.wr_data_0;
      reg_data(869)( 9 downto  0)  <= DEFAULT_TAR_CTRL_t.PL_STATION.PL_OUT.PL_MEM(5).wr_data.wr_data_1;

    elsif clk_axi'event and clk_axi = '1' then  -- rising clock edge
      Ctrl.ACTIONS.RESET <= '0';
      Ctrl.ACTIONS.ENABLE <= '0';
      Ctrl.ACTIONS.DISABLE <= '0';
      Ctrl.ACTIONS.FREEZE <= '0';
      Ctrl.PL_STATION.PL_INN.PL_MEM(0).wr_req <= '0';
      Ctrl.PL_STATION.PL_INN.PL_MEM(0).wr_ack <= '0';
      Ctrl.PL_STATION.PL_INN.PL_MEM(0).rd_req <= '0';
      Ctrl.PL_STATION.PL_INN.PL_MEM(0).rd_ack <= '0';
      Ctrl.PL_STATION.PL_INN.PL_MEM(0).flush_req <= '0';
      Ctrl.PL_STATION.PL_INN.PL_MEM(1).wr_req <= '0';
      Ctrl.PL_STATION.PL_INN.PL_MEM(1).wr_ack <= '0';
      Ctrl.PL_STATION.PL_INN.PL_MEM(1).rd_req <= '0';
      Ctrl.PL_STATION.PL_INN.PL_MEM(1).rd_ack <= '0';
      Ctrl.PL_STATION.PL_INN.PL_MEM(1).flush_req <= '0';
      Ctrl.PL_STATION.PL_INN.PL_MEM(2).wr_req <= '0';
      Ctrl.PL_STATION.PL_INN.PL_MEM(2).wr_ack <= '0';
      Ctrl.PL_STATION.PL_INN.PL_MEM(2).rd_req <= '0';
      Ctrl.PL_STATION.PL_INN.PL_MEM(2).rd_ack <= '0';
      Ctrl.PL_STATION.PL_INN.PL_MEM(2).flush_req <= '0';
      Ctrl.PL_STATION.PL_INN.PL_MEM(3).wr_req <= '0';
      Ctrl.PL_STATION.PL_INN.PL_MEM(3).wr_ack <= '0';
      Ctrl.PL_STATION.PL_INN.PL_MEM(3).rd_req <= '0';
      Ctrl.PL_STATION.PL_INN.PL_MEM(3).rd_ack <= '0';
      Ctrl.PL_STATION.PL_INN.PL_MEM(3).flush_req <= '0';
      Ctrl.PL_STATION.PL_INN.PL_MEM(4).wr_req <= '0';
      Ctrl.PL_STATION.PL_INN.PL_MEM(4).wr_ack <= '0';
      Ctrl.PL_STATION.PL_INN.PL_MEM(4).rd_req <= '0';
      Ctrl.PL_STATION.PL_INN.PL_MEM(4).rd_ack <= '0';
      Ctrl.PL_STATION.PL_INN.PL_MEM(4).flush_req <= '0';
      Ctrl.PL_STATION.PL_INN.PL_MEM(5).wr_req <= '0';
      Ctrl.PL_STATION.PL_INN.PL_MEM(5).wr_ack <= '0';
      Ctrl.PL_STATION.PL_INN.PL_MEM(5).rd_req <= '0';
      Ctrl.PL_STATION.PL_INN.PL_MEM(5).rd_ack <= '0';
      Ctrl.PL_STATION.PL_INN.PL_MEM(5).flush_req <= '0';
      Ctrl.PL_STATION.PL_MID.PL_MEM(0).wr_req <= '0';
      Ctrl.PL_STATION.PL_MID.PL_MEM(0).wr_ack <= '0';
      Ctrl.PL_STATION.PL_MID.PL_MEM(0).rd_req <= '0';
      Ctrl.PL_STATION.PL_MID.PL_MEM(0).rd_ack <= '0';
      Ctrl.PL_STATION.PL_MID.PL_MEM(0).flush_req <= '0';
      Ctrl.PL_STATION.PL_MID.PL_MEM(1).wr_req <= '0';
      Ctrl.PL_STATION.PL_MID.PL_MEM(1).wr_ack <= '0';
      Ctrl.PL_STATION.PL_MID.PL_MEM(1).rd_req <= '0';
      Ctrl.PL_STATION.PL_MID.PL_MEM(1).rd_ack <= '0';
      Ctrl.PL_STATION.PL_MID.PL_MEM(1).flush_req <= '0';
      Ctrl.PL_STATION.PL_MID.PL_MEM(2).wr_req <= '0';
      Ctrl.PL_STATION.PL_MID.PL_MEM(2).wr_ack <= '0';
      Ctrl.PL_STATION.PL_MID.PL_MEM(2).rd_req <= '0';
      Ctrl.PL_STATION.PL_MID.PL_MEM(2).rd_ack <= '0';
      Ctrl.PL_STATION.PL_MID.PL_MEM(2).flush_req <= '0';
      Ctrl.PL_STATION.PL_MID.PL_MEM(3).wr_req <= '0';
      Ctrl.PL_STATION.PL_MID.PL_MEM(3).wr_ack <= '0';
      Ctrl.PL_STATION.PL_MID.PL_MEM(3).rd_req <= '0';
      Ctrl.PL_STATION.PL_MID.PL_MEM(3).rd_ack <= '0';
      Ctrl.PL_STATION.PL_MID.PL_MEM(3).flush_req <= '0';
      Ctrl.PL_STATION.PL_MID.PL_MEM(4).wr_req <= '0';
      Ctrl.PL_STATION.PL_MID.PL_MEM(4).wr_ack <= '0';
      Ctrl.PL_STATION.PL_MID.PL_MEM(4).rd_req <= '0';
      Ctrl.PL_STATION.PL_MID.PL_MEM(4).rd_ack <= '0';
      Ctrl.PL_STATION.PL_MID.PL_MEM(4).flush_req <= '0';
      Ctrl.PL_STATION.PL_MID.PL_MEM(5).wr_req <= '0';
      Ctrl.PL_STATION.PL_MID.PL_MEM(5).wr_ack <= '0';
      Ctrl.PL_STATION.PL_MID.PL_MEM(5).rd_req <= '0';
      Ctrl.PL_STATION.PL_MID.PL_MEM(5).rd_ack <= '0';
      Ctrl.PL_STATION.PL_MID.PL_MEM(5).flush_req <= '0';
      Ctrl.PL_STATION.PL_OUT.PL_MEM(0).wr_req <= '0';
      Ctrl.PL_STATION.PL_OUT.PL_MEM(0).wr_ack <= '0';
      Ctrl.PL_STATION.PL_OUT.PL_MEM(0).rd_req <= '0';
      Ctrl.PL_STATION.PL_OUT.PL_MEM(0).rd_ack <= '0';
      Ctrl.PL_STATION.PL_OUT.PL_MEM(0).flush_req <= '0';
      Ctrl.PL_STATION.PL_OUT.PL_MEM(1).wr_req <= '0';
      Ctrl.PL_STATION.PL_OUT.PL_MEM(1).wr_ack <= '0';
      Ctrl.PL_STATION.PL_OUT.PL_MEM(1).rd_req <= '0';
      Ctrl.PL_STATION.PL_OUT.PL_MEM(1).rd_ack <= '0';
      Ctrl.PL_STATION.PL_OUT.PL_MEM(1).flush_req <= '0';
      Ctrl.PL_STATION.PL_OUT.PL_MEM(2).wr_req <= '0';
      Ctrl.PL_STATION.PL_OUT.PL_MEM(2).wr_ack <= '0';
      Ctrl.PL_STATION.PL_OUT.PL_MEM(2).rd_req <= '0';
      Ctrl.PL_STATION.PL_OUT.PL_MEM(2).rd_ack <= '0';
      Ctrl.PL_STATION.PL_OUT.PL_MEM(2).flush_req <= '0';
      Ctrl.PL_STATION.PL_OUT.PL_MEM(3).wr_req <= '0';
      Ctrl.PL_STATION.PL_OUT.PL_MEM(3).wr_ack <= '0';
      Ctrl.PL_STATION.PL_OUT.PL_MEM(3).rd_req <= '0';
      Ctrl.PL_STATION.PL_OUT.PL_MEM(3).rd_ack <= '0';
      Ctrl.PL_STATION.PL_OUT.PL_MEM(3).flush_req <= '0';
      Ctrl.PL_STATION.PL_OUT.PL_MEM(4).wr_req <= '0';
      Ctrl.PL_STATION.PL_OUT.PL_MEM(4).wr_ack <= '0';
      Ctrl.PL_STATION.PL_OUT.PL_MEM(4).rd_req <= '0';
      Ctrl.PL_STATION.PL_OUT.PL_MEM(4).rd_ack <= '0';
      Ctrl.PL_STATION.PL_OUT.PL_MEM(4).flush_req <= '0';
      Ctrl.PL_STATION.PL_OUT.PL_MEM(5).wr_req <= '0';
      Ctrl.PL_STATION.PL_OUT.PL_MEM(5).wr_ack <= '0';
      Ctrl.PL_STATION.PL_OUT.PL_MEM(5).rd_req <= '0';
      Ctrl.PL_STATION.PL_OUT.PL_MEM(5).rd_ack <= '0';
      Ctrl.PL_STATION.PL_OUT.PL_MEM(5).flush_req <= '0';
      

      
      if localWrEn = '1' then
        case to_integer(unsigned(localAddress(9 downto 0))) is
        when 0 => --0x0
          Ctrl.ACTIONS.RESET                          <=  localWrData( 0);               
          Ctrl.ACTIONS.ENABLE                         <=  localWrData( 1);               
          Ctrl.ACTIONS.DISABLE                        <=  localWrData( 2);               
          Ctrl.ACTIONS.FREEZE                         <=  localWrData( 3);               
        when 1 => --0x1
          reg_data(1)( 4)                             <=  localWrData( 4);                -- 
          reg_data(1)( 5)                             <=  localWrData( 5);                -- 
          reg_data(1)( 6)                             <=  localWrData( 6);                -- 
        when 834 => --0x342
          reg_data(834)(11 downto  0)                 <=  localWrData(11 downto  0);      -- wr_Address
          reg_data(834)(27 downto 16)                 <=  localWrData(27 downto 16);      -- rd_Address
        when 594 => --0x252
          reg_data(594)(11 downto  0)                 <=  localWrData(11 downto  0);      -- wr_Address
          reg_data(594)(27 downto 16)                 <=  localWrData(27 downto 16);      -- rd_Address
        when 848 => --0x350
          Ctrl.PL_STATION.PL_OUT.PL_MEM(4).wr_req     <=  localWrData( 0);               
          Ctrl.PL_STATION.PL_OUT.PL_MEM(4).wr_ack     <=  localWrData( 1);               
          Ctrl.PL_STATION.PL_OUT.PL_MEM(4).rd_req     <=  localWrData( 2);               
          Ctrl.PL_STATION.PL_OUT.PL_MEM(4).rd_ack     <=  localWrData( 3);               
          Ctrl.PL_STATION.PL_OUT.PL_MEM(4).flush_req  <=  localWrData( 4);               
        when 578 => --0x242
          reg_data(578)(11 downto  0)                 <=  localWrData(11 downto  0);      -- wr_Address
          reg_data(578)(27 downto 16)                 <=  localWrData(27 downto 16);      -- rd_Address
        when 597 => --0x255
          reg_data(597)( 9 downto  0)                 <=  localWrData( 9 downto  0);      -- Write Data 1
        when 272 => --0x110
          Ctrl.PL_STATION.PL_INN.PL_MEM(0).wr_req     <=  localWrData( 0);               
          Ctrl.PL_STATION.PL_INN.PL_MEM(0).wr_ack     <=  localWrData( 1);               
          Ctrl.PL_STATION.PL_INN.PL_MEM(0).rd_req     <=  localWrData( 2);               
          Ctrl.PL_STATION.PL_INN.PL_MEM(0).rd_ack     <=  localWrData( 3);               
          Ctrl.PL_STATION.PL_INN.PL_MEM(0).flush_req  <=  localWrData( 4);               
        when 274 => --0x112
          reg_data(274)(11 downto  0)                 <=  localWrData(11 downto  0);      -- wr_Address
          reg_data(274)(27 downto 16)                 <=  localWrData(27 downto 16);      -- rd_Address
        when 276 => --0x114
          reg_data(276)(31 downto  0)                 <=  localWrData(31 downto  0);      -- Write Data 0
        when 277 => --0x115
          reg_data(277)( 9 downto  0)                 <=  localWrData( 9 downto  0);      -- Write Data 1
        when 853 => --0x355
          reg_data(853)( 9 downto  0)                 <=  localWrData( 9 downto  0);      -- Write Data 1
        when 576 => --0x240
          Ctrl.PL_STATION.PL_MID.PL_MEM(3).wr_req     <=  localWrData( 0);               
          Ctrl.PL_STATION.PL_MID.PL_MEM(3).wr_ack     <=  localWrData( 1);               
          Ctrl.PL_STATION.PL_MID.PL_MEM(3).rd_req     <=  localWrData( 2);               
          Ctrl.PL_STATION.PL_MID.PL_MEM(3).rd_ack     <=  localWrData( 3);               
          Ctrl.PL_STATION.PL_MID.PL_MEM(3).flush_req  <=  localWrData( 4);               
        when 580 => --0x244
          reg_data(580)(31 downto  0)                 <=  localWrData(31 downto  0);      -- Write Data 0
        when 802 => --0x322
          reg_data(802)(11 downto  0)                 <=  localWrData(11 downto  0);      -- wr_Address
          reg_data(802)(27 downto 16)                 <=  localWrData(27 downto 16);      -- rd_Address
        when 866 => --0x362
          reg_data(866)(11 downto  0)                 <=  localWrData(11 downto  0);      -- wr_Address
          reg_data(866)(27 downto 16)                 <=  localWrData(27 downto 16);      -- rd_Address
        when 581 => --0x245
          reg_data(581)( 9 downto  0)                 <=  localWrData( 9 downto  0);      -- Write Data 1
        when 288 => --0x120
          Ctrl.PL_STATION.PL_INN.PL_MEM(1).wr_req     <=  localWrData( 0);               
          Ctrl.PL_STATION.PL_INN.PL_MEM(1).wr_ack     <=  localWrData( 1);               
          Ctrl.PL_STATION.PL_INN.PL_MEM(1).rd_req     <=  localWrData( 2);               
          Ctrl.PL_STATION.PL_INN.PL_MEM(1).rd_ack     <=  localWrData( 3);               
          Ctrl.PL_STATION.PL_INN.PL_MEM(1).flush_req  <=  localWrData( 4);               
        when 560 => --0x230
          Ctrl.PL_STATION.PL_MID.PL_MEM(2).wr_req     <=  localWrData( 0);               
          Ctrl.PL_STATION.PL_MID.PL_MEM(2).wr_ack     <=  localWrData( 1);               
          Ctrl.PL_STATION.PL_MID.PL_MEM(2).rd_req     <=  localWrData( 2);               
          Ctrl.PL_STATION.PL_MID.PL_MEM(2).rd_ack     <=  localWrData( 3);               
          Ctrl.PL_STATION.PL_MID.PL_MEM(2).flush_req  <=  localWrData( 4);               
        when 290 => --0x122
          reg_data(290)(11 downto  0)                 <=  localWrData(11 downto  0);      -- wr_Address
          reg_data(290)(27 downto 16)                 <=  localWrData(27 downto 16);      -- rd_Address
        when 292 => --0x124
          reg_data(292)(31 downto  0)                 <=  localWrData(31 downto  0);      -- Write Data 0
        when 293 => --0x125
          reg_data(293)( 9 downto  0)                 <=  localWrData( 9 downto  0);      -- Write Data 1
        when 832 => --0x340
          Ctrl.PL_STATION.PL_OUT.PL_MEM(3).wr_req     <=  localWrData( 0);               
          Ctrl.PL_STATION.PL_OUT.PL_MEM(3).wr_ack     <=  localWrData( 1);               
          Ctrl.PL_STATION.PL_OUT.PL_MEM(3).rd_req     <=  localWrData( 2);               
          Ctrl.PL_STATION.PL_OUT.PL_MEM(3).rd_ack     <=  localWrData( 3);               
          Ctrl.PL_STATION.PL_OUT.PL_MEM(3).flush_req  <=  localWrData( 4);               
        when 821 => --0x335
          reg_data(821)( 9 downto  0)                 <=  localWrData( 9 downto  0);      -- Write Data 1
        when 562 => --0x232
          reg_data(562)(11 downto  0)                 <=  localWrData(11 downto  0);      -- wr_Address
          reg_data(562)(27 downto 16)                 <=  localWrData(27 downto 16);      -- rd_Address
        when 304 => --0x130
          Ctrl.PL_STATION.PL_INN.PL_MEM(2).wr_req     <=  localWrData( 0);               
          Ctrl.PL_STATION.PL_INN.PL_MEM(2).wr_ack     <=  localWrData( 1);               
          Ctrl.PL_STATION.PL_INN.PL_MEM(2).rd_req     <=  localWrData( 2);               
          Ctrl.PL_STATION.PL_INN.PL_MEM(2).rd_ack     <=  localWrData( 3);               
          Ctrl.PL_STATION.PL_INN.PL_MEM(2).flush_req  <=  localWrData( 4);               
        when 868 => --0x364
          reg_data(868)(31 downto  0)                 <=  localWrData(31 downto  0);      -- Write Data 0
        when 306 => --0x132
          reg_data(306)(11 downto  0)                 <=  localWrData(11 downto  0);      -- wr_Address
          reg_data(306)(27 downto 16)                 <=  localWrData(27 downto 16);      -- rd_Address
        when 308 => --0x134
          reg_data(308)(31 downto  0)                 <=  localWrData(31 downto  0);      -- Write Data 0
        when 309 => --0x135
          reg_data(309)( 9 downto  0)                 <=  localWrData( 9 downto  0);      -- Write Data 1
        when 837 => --0x345
          reg_data(837)( 9 downto  0)                 <=  localWrData( 9 downto  0);      -- Write Data 1
        when 820 => --0x334
          reg_data(820)(31 downto  0)                 <=  localWrData(31 downto  0);      -- Write Data 0
        when 564 => --0x234
          reg_data(564)(31 downto  0)                 <=  localWrData(31 downto  0);      -- Write Data 0
        when 786 => --0x312
          reg_data(786)(11 downto  0)                 <=  localWrData(11 downto  0);      -- wr_Address
          reg_data(786)(27 downto 16)                 <=  localWrData(27 downto 16);      -- rd_Address
        when 816 => --0x330
          Ctrl.PL_STATION.PL_OUT.PL_MEM(2).wr_req     <=  localWrData( 0);               
          Ctrl.PL_STATION.PL_OUT.PL_MEM(2).wr_ack     <=  localWrData( 1);               
          Ctrl.PL_STATION.PL_OUT.PL_MEM(2).rd_req     <=  localWrData( 2);               
          Ctrl.PL_STATION.PL_OUT.PL_MEM(2).rd_ack     <=  localWrData( 3);               
          Ctrl.PL_STATION.PL_OUT.PL_MEM(2).flush_req  <=  localWrData( 4);               
        when 608 => --0x260
          Ctrl.PL_STATION.PL_MID.PL_MEM(5).wr_req     <=  localWrData( 0);               
          Ctrl.PL_STATION.PL_MID.PL_MEM(5).wr_ack     <=  localWrData( 1);               
          Ctrl.PL_STATION.PL_MID.PL_MEM(5).rd_req     <=  localWrData( 2);               
          Ctrl.PL_STATION.PL_MID.PL_MEM(5).rd_ack     <=  localWrData( 3);               
          Ctrl.PL_STATION.PL_MID.PL_MEM(5).flush_req  <=  localWrData( 4);               
        when 565 => --0x235
          reg_data(565)( 9 downto  0)                 <=  localWrData( 9 downto  0);      -- Write Data 1
        when 320 => --0x140
          Ctrl.PL_STATION.PL_INN.PL_MEM(3).wr_req     <=  localWrData( 0);               
          Ctrl.PL_STATION.PL_INN.PL_MEM(3).wr_ack     <=  localWrData( 1);               
          Ctrl.PL_STATION.PL_INN.PL_MEM(3).rd_req     <=  localWrData( 2);               
          Ctrl.PL_STATION.PL_INN.PL_MEM(3).rd_ack     <=  localWrData( 3);               
          Ctrl.PL_STATION.PL_INN.PL_MEM(3).flush_req  <=  localWrData( 4);               
        when 544 => --0x220
          Ctrl.PL_STATION.PL_MID.PL_MEM(1).wr_req     <=  localWrData( 0);               
          Ctrl.PL_STATION.PL_MID.PL_MEM(1).wr_ack     <=  localWrData( 1);               
          Ctrl.PL_STATION.PL_MID.PL_MEM(1).rd_req     <=  localWrData( 2);               
          Ctrl.PL_STATION.PL_MID.PL_MEM(1).rd_ack     <=  localWrData( 3);               
          Ctrl.PL_STATION.PL_MID.PL_MEM(1).flush_req  <=  localWrData( 4);               
        when 322 => --0x142
          reg_data(322)(11 downto  0)                 <=  localWrData(11 downto  0);      -- wr_Address
          reg_data(322)(27 downto 16)                 <=  localWrData(27 downto 16);      -- rd_Address
        when 324 => --0x144
          reg_data(324)(31 downto  0)                 <=  localWrData(31 downto  0);      -- Write Data 0
        when 325 => --0x145
          reg_data(325)( 9 downto  0)                 <=  localWrData( 9 downto  0);      -- Write Data 1
        when 546 => --0x222
          reg_data(546)(11 downto  0)                 <=  localWrData(11 downto  0);      -- wr_Address
          reg_data(546)(27 downto 16)                 <=  localWrData(27 downto 16);      -- rd_Address
        when 336 => --0x150
          Ctrl.PL_STATION.PL_INN.PL_MEM(4).wr_req     <=  localWrData( 0);               
          Ctrl.PL_STATION.PL_INN.PL_MEM(4).wr_ack     <=  localWrData( 1);               
          Ctrl.PL_STATION.PL_INN.PL_MEM(4).rd_req     <=  localWrData( 2);               
          Ctrl.PL_STATION.PL_INN.PL_MEM(4).rd_ack     <=  localWrData( 3);               
          Ctrl.PL_STATION.PL_INN.PL_MEM(4).flush_req  <=  localWrData( 4);               
        when 612 => --0x264
          reg_data(612)(31 downto  0)                 <=  localWrData(31 downto  0);      -- Write Data 0
        when 338 => --0x152
          reg_data(338)(11 downto  0)                 <=  localWrData(11 downto  0);      -- wr_Address
          reg_data(338)(27 downto 16)                 <=  localWrData(27 downto 16);      -- rd_Address
        when 340 => --0x154
          reg_data(340)(31 downto  0)                 <=  localWrData(31 downto  0);      -- Write Data 0
        when 341 => --0x155
          reg_data(341)( 9 downto  0)                 <=  localWrData( 9 downto  0);      -- Write Data 1
        when 804 => --0x324
          reg_data(804)(31 downto  0)                 <=  localWrData(31 downto  0);      -- Write Data 0
        when 548 => --0x224
          reg_data(548)(31 downto  0)                 <=  localWrData(31 downto  0);      -- Write Data 0
        when 800 => --0x320
          Ctrl.PL_STATION.PL_OUT.PL_MEM(1).wr_req     <=  localWrData( 0);               
          Ctrl.PL_STATION.PL_OUT.PL_MEM(1).wr_ack     <=  localWrData( 1);               
          Ctrl.PL_STATION.PL_OUT.PL_MEM(1).rd_req     <=  localWrData( 2);               
          Ctrl.PL_STATION.PL_OUT.PL_MEM(1).rd_ack     <=  localWrData( 3);               
          Ctrl.PL_STATION.PL_OUT.PL_MEM(1).flush_req  <=  localWrData( 4);               
        when 836 => --0x344
          reg_data(836)(31 downto  0)                 <=  localWrData(31 downto  0);      -- Write Data 0
        when 549 => --0x225
          reg_data(549)( 9 downto  0)                 <=  localWrData( 9 downto  0);      -- Write Data 1
        when 352 => --0x160
          Ctrl.PL_STATION.PL_INN.PL_MEM(5).wr_req     <=  localWrData( 0);               
          Ctrl.PL_STATION.PL_INN.PL_MEM(5).wr_ack     <=  localWrData( 1);               
          Ctrl.PL_STATION.PL_INN.PL_MEM(5).rd_req     <=  localWrData( 2);               
          Ctrl.PL_STATION.PL_INN.PL_MEM(5).rd_ack     <=  localWrData( 3);               
          Ctrl.PL_STATION.PL_INN.PL_MEM(5).flush_req  <=  localWrData( 4);               
        when 528 => --0x210
          Ctrl.PL_STATION.PL_MID.PL_MEM(0).wr_req     <=  localWrData( 0);               
          Ctrl.PL_STATION.PL_MID.PL_MEM(0).wr_ack     <=  localWrData( 1);               
          Ctrl.PL_STATION.PL_MID.PL_MEM(0).rd_req     <=  localWrData( 2);               
          Ctrl.PL_STATION.PL_MID.PL_MEM(0).rd_ack     <=  localWrData( 3);               
          Ctrl.PL_STATION.PL_MID.PL_MEM(0).flush_req  <=  localWrData( 4);               
        when 354 => --0x162
          reg_data(354)(11 downto  0)                 <=  localWrData(11 downto  0);      -- wr_Address
          reg_data(354)(27 downto 16)                 <=  localWrData(27 downto 16);      -- rd_Address
        when 852 => --0x354
          reg_data(852)(31 downto  0)                 <=  localWrData(31 downto  0);      -- Write Data 0
        when 356 => --0x164
          reg_data(356)(31 downto  0)                 <=  localWrData(31 downto  0);      -- Write Data 0
        when 357 => --0x165
          reg_data(357)( 9 downto  0)                 <=  localWrData( 9 downto  0);      -- Write Data 1
        when 864 => --0x360
          Ctrl.PL_STATION.PL_OUT.PL_MEM(5).wr_req     <=  localWrData( 0);               
          Ctrl.PL_STATION.PL_OUT.PL_MEM(5).wr_ack     <=  localWrData( 1);               
          Ctrl.PL_STATION.PL_OUT.PL_MEM(5).rd_req     <=  localWrData( 2);               
          Ctrl.PL_STATION.PL_OUT.PL_MEM(5).rd_ack     <=  localWrData( 3);               
          Ctrl.PL_STATION.PL_OUT.PL_MEM(5).flush_req  <=  localWrData( 4);               
        when 610 => --0x262
          reg_data(610)(11 downto  0)                 <=  localWrData(11 downto  0);      -- wr_Address
          reg_data(610)(27 downto 16)                 <=  localWrData(27 downto 16);      -- rd_Address
        when 850 => --0x352
          reg_data(850)(11 downto  0)                 <=  localWrData(11 downto  0);      -- wr_Address
          reg_data(850)(27 downto 16)                 <=  localWrData(27 downto 16);      -- rd_Address
        when 530 => --0x212
          reg_data(530)(11 downto  0)                 <=  localWrData(11 downto  0);      -- wr_Address
          reg_data(530)(27 downto 16)                 <=  localWrData(27 downto 16);      -- rd_Address
        when 613 => --0x265
          reg_data(613)( 9 downto  0)                 <=  localWrData( 9 downto  0);      -- Write Data 1
        when 596 => --0x254
          reg_data(596)(31 downto  0)                 <=  localWrData(31 downto  0);      -- Write Data 0
        when 805 => --0x325
          reg_data(805)( 9 downto  0)                 <=  localWrData( 9 downto  0);      -- Write Data 1
        when 788 => --0x314
          reg_data(788)(31 downto  0)                 <=  localWrData(31 downto  0);      -- Write Data 0
        when 869 => --0x365
          reg_data(869)( 9 downto  0)                 <=  localWrData( 9 downto  0);      -- Write Data 1
        when 592 => --0x250
          Ctrl.PL_STATION.PL_MID.PL_MEM(4).wr_req     <=  localWrData( 0);               
          Ctrl.PL_STATION.PL_MID.PL_MEM(4).wr_ack     <=  localWrData( 1);               
          Ctrl.PL_STATION.PL_MID.PL_MEM(4).rd_req     <=  localWrData( 2);               
          Ctrl.PL_STATION.PL_MID.PL_MEM(4).rd_ack     <=  localWrData( 3);               
          Ctrl.PL_STATION.PL_MID.PL_MEM(4).flush_req  <=  localWrData( 4);               
        when 532 => --0x214
          reg_data(532)(31 downto  0)                 <=  localWrData(31 downto  0);      -- Write Data 0
        when 789 => --0x315
          reg_data(789)( 9 downto  0)                 <=  localWrData( 9 downto  0);      -- Write Data 1
        when 818 => --0x332
          reg_data(818)(11 downto  0)                 <=  localWrData(11 downto  0);      -- wr_Address
          reg_data(818)(27 downto 16)                 <=  localWrData(27 downto 16);      -- rd_Address
        when 784 => --0x310
          Ctrl.PL_STATION.PL_OUT.PL_MEM(0).wr_req     <=  localWrData( 0);               
          Ctrl.PL_STATION.PL_OUT.PL_MEM(0).wr_ack     <=  localWrData( 1);               
          Ctrl.PL_STATION.PL_OUT.PL_MEM(0).rd_req     <=  localWrData( 2);               
          Ctrl.PL_STATION.PL_OUT.PL_MEM(0).rd_ack     <=  localWrData( 3);               
          Ctrl.PL_STATION.PL_OUT.PL_MEM(0).flush_req  <=  localWrData( 4);               
        when 533 => --0x215
          reg_data(533)( 9 downto  0)                 <=  localWrData( 9 downto  0);      -- Write Data 1

          when others => null;
        end case;
      end if;
    end if;
  end process reg_writes;


end architecture behavioral;
