#################### ull_vu13_b3a_ucm_mpl_hps_csf Project ###########################
GEN:ull_vu13_b3a_ucm_mpl_hps_csf:
    extends: .generate_project
    variables:
      extends: .vars
      PROJECT_NAME: ull_vu13_b3a_ucm_mpl_hps_csf
      HOG_ONLY_SYNTH: 1 # if 1 runs only the synthesis
      
    tags:
      - heavy-duty
      - hog

SIM:ull_vu13_b3a_ucm_mpl_hps_csf:
    extends: .simulate_project
    variables:
      extends: .vars
      PROJECT_NAME: ull_vu13_b3a_ucm_mpl_hps_csf
    allow_failure: false
    tags:
      - normal-ops
      - hog
    artifacts:
      name: user_sim
      paths:
        - $CI_PROJECT_DIR/Projects/$PROJECT_NAME/$PROJECT_NAME.sim
        - $CI_PROJECT_DIR/SkippedProjects/$PROJECT_NAME
      expire_in: 30 day

# sim_comp:ull_ku15_b3a_ucm_mpl_hps_csf_questa:
#     extends: .simulate_project_comp
#     variables:
#       extends: .vars
#       PROJECT_NAME: ull_ku15_b3a_ucm_mpl_hps_csf_questa

sim_check:ull_vu13_b3a_ucm_mpl_hps_csf:
    extends: .sim_check
    variables:
      extends: .vars
      PROJECT_NAME: ull_vu13_b3a_ucm_mpl_hps_csf
