#################### ult_tp_csf Project ###########################
generate_project:ult_tp_csf:
    extends: .generate_project
    variables:
      extends: .vars
      PROJECT_NAME: ult_tp_csf
      HOG_ONLY_SYNTH: 1 # if 1 runs only the synthesis

simulate_project:ult_tp_csf:
    extends: .simulate_project
    variables:
      extends: .vars
      PROJECT_NAME: ult_tp_csf
    allow_failure: false


# sim_comp:ult_tp_csf_questa:
#     extends: .sim_comp
#     variables:
#       extends: .vars
#       PROJECT_NAME: ult_tp_csf_questa

sim_check:ult_tp_csf:
    extends: .sim_check
    variables:
      extends: .vars
      PROJECT_NAME: ult_tp_csf
