#################### ull_ku15_b3a_ucm_mpl_hps_csf Project ###########################
GEN:ull_ku15_b3a_ucm_mpl_hps_csf:
    extends: .generate_project
    variables:
      extends: .vars
      PROJECT_NAME: ull_ku15_b3a_ucm_mpl_hps_csf
      HOG_ONLY_SYNTH: 1 # if 1 runs only the synthesis
      
    tags:
      - heavy-duty
      - hog

SIM:ull_ku15_b3a_ucm_mpl_hps_csf:
    extends: .simulate_project
    variables:
      extends: .vars
      PROJECT_NAME: ull_ku15_b3a_ucm_mpl_hps_csf
    allow_failure: false
    before_script:
      - export PATH="/opt/Xilinx/Vivado/2019.2/bin:/opt/questa/2019.4_4/questasim/linux_x86_64:$PATH"
    tags:
      - questa
      - hog
      

# sim_comp:ull_ku15_b3a_ucm_mpl_hps_csf_questa:
#     extends: .simulate_project_comp
#     variables:
#       extends: .vars
#       PROJECT_NAME: ull_ku15_b3a_ucm_mpl_hps_csf_questa


RIV:ull_ku15_b3a_ucm_mpl_hps_csf:
    extends: .riviera_sim
    variables:
      extends: .riviera_vars
      PROJECT_NAME: ull_ku15_b3a_ucm_mpl_hps_csf
      HOG_CHECK_PROJVER: 0
      # HOG_PATH: "/opt/Xilinx/Vivado/2019.2/bin:/opt//mnt/vd/Xilinx/Vivado/2019.2/bin:/afs/cern.ch/project/parc/riviera20214/bin/"
      HOG_SIMULATION_LIB_PATH: "/home/l0mdtel/RivieraLib"
    before_script:
      - export PATH="/opt/Xilinx/Vivado/2019.2/bin:/opt/Aldec/Riviera-PRO-2021.04-x64/bin:$PATH"

CHK:ull_ku15_b3a_ucm_mpl_hps_csf:
  extends: .sim_check
  variables:
    extends: .vars
    PROJECT_NAME: ull_ku15_b3a_ucm_mpl_hps_csf
  needs: ["SIM:ull_ku15_b3a_ucm_mpl_hps_csf","RIV:ull_ku15_b3a_ucm_mpl_hps_csf"]
