#################### ull_ku15_b3a_ucm_mpl_hps_csf Project ###########################
GEN:ull_ku15_b3a_ucm_mpl_hps_csf:
    extends: .GEN
    variables:
      extends: .vars
      PROJECT_NAME: ull_ku15_b3a_ucm_mpl_hps_csf
      HOG_ONLY_SYNTH: 1 # if 1 runs only the synthesis
    tags:
      - heavy-duty
      - hog

SIM:ull_ku15_b3a_ucm_mpl_hps_csf:
    extends: .SIM
    variables:
      extends: .vars
      PROJECT_NAME: ull_ku15_b3a_ucm_mpl_hps_csf
    allow_failure: false
    tags:
      - heavy-duty
      - hog

# sim_comp:ull_ku15_b3a_ucm_mpl_hps_csf_questa:
#     extends: .sim_comp
#     variables:
#       extends: .vars
#       PROJECT_NAME: ull_ku15_b3a_ucm_mpl_hps_csf_questa

sim_check:ull_ku15_b3a_ucm_mpl_hps_csf:
    extends: .sim_check
    variables:
      extends: .vars
      PROJECT_NAME: ull_ku15_b3a_ucm_mpl_hps_csf
