// This file was auto-generated by YML2HDL tool.
// https://gitlab.com/tcpaiva/yml2hdl

`ifndef DAQ_DATA_PATH_DEFS_SVH
`define DAQ_DATA_PATH_DEFS_SVH

`include <common_ieee.svh>

`include <ttc_defs.svh>

`include <daq_config_defs.svh>
`include <daq_defs.svh>


  typedef struct packed {
    ttc_sys_rt   sys;
    ttc_fmt_vt   ttc;
    ctrl_to_daq_rt   ctrl;
    daq_stream_rt   stream_0;
    daq_stream_rt   stream_1;
    daq_stream_rt   stream_2;
    daq_stream_rt   stream_3;
    felix_to_daq_rt   f2e0;
    felix_to_daq_rt   f2e1;
    felix_to_daq_rt   f2e2;
    felix_to_daq_rt   f2e3;
  } daq_data_path_irt;

  typedef struct packed {
    daq_to_status_rt   status0;
    daq_to_felix_rt   f2e0;
    daq_to_status_rt   status1;
    daq_to_felix_rt   f2e1;
    daq_to_status_rt   status2;
    daq_to_felix_rt   f2e2;
    daq_to_status_rt   status3;
    daq_to_felix_rt   f2e3;
  } daq_data_path_ort;

  typedef struct packed {
    daq_data_path_irt   i;
    daq_data_path_ort   o;
  } daq_data_path_ert;



`endif // DAQ_DATA_PATH_DEFS_SVH
