# #################### CSF Project ###########################
generate_project:csf.1:
    extends: .generate_project
    variables:
      extends: .vars
      PROJECT_NAME: csf.1
      HOG_ONLY_SYNTH: 1 # if 1 runs only the synthesis

# simulate_project:csf.1:
#     extends: .simulate_project
#     variables:
#       extends: .vars
#       PROJECT_NAME: csf.1