# #################### CSF Project ###########################
GEN:csf.1:
    extends: .generate_project
    variables:
      extends: .vars
      PROJECT_NAME: csf.1
      HOG_ONLY_SYNTH: 1 # if 1 runs only the synthesis
      HOG_CHECK_SYNTAX : 1
    tags:
      - normal-ops
      - hog
# SIM:csf.1:
#     extends: .simulate_project
#     variables:
#       extends: .vars
#       PROJECT_NAME: csf.1