#################### hal Project ###########################
GEN:hal:
    extends: .GEN
    variables:
      extends: .vars
      PROJECT_NAME: hal
      HOG_ONLY_SYNTH: 1 # if 1 runs only the synthesis

# SIM:hal:
#     extends: .SIM
#     variables:
#       extends: .vars
#       PROJECT_NAME: hal
