#################### hal Project ###########################
generate_project:hal:
    extends: .generate_project
    variables:
      extends: .vars
      PROJECT_NAME: hal
      HOG_ONLY_SYNTH: 1 # if 1 runs only the synthesis

# simulate_project:hal:
#     extends: .simulate_project
#     variables:
#       extends: .vars
#       PROJECT_NAME: hal
