#################### BA3_ucm010_ku15_1.2_vu13 Project ###########################
GEN:BA3_ucm010_ku15:
  extends: .generate_project
  variables:
    extends: .vars
    PROJECT_NAME: MainBlocks/BA3_ucm010_ku15
    HOG_ONLY_SYNTH: 1 # if 1 runs only the synthesis
  tags:
    - normal-ops


# SIM:BA3_ucm010_ku15_vivado:
#     extends: .simulate_project
#     variables:
#       extends: .vars
#       PROJECT_NAME: MainBlocks/BA3_ucm010_ku15

SIM:BA3_ucm010_ku15_questa:
    extends: .simulate_project
    variables:
      extends: .vars
      PROJECT_NAME: MainBlocks/BA3_ucm010_ku15
    tags:
      - normal-ops
    allow_failure: false

RIV:BA3_ucm010_ku15_riviera:
    extends: .riviera_sim
    variables:
      extends: .vars
      PROJECT_NAME: MainBlocks/BA3_ucm010_ku15
    allow_failure: true

COMP:BA3_ucm010_ku15:
  extends: .sim_comp
  variables:
    extends: .vars
    PROJECT_NAME: MainBlocks/BA3_ucm010_ku15
    PROJECT_Q_NAME: MainBlocks/BA3_ucm010_ku15_questa
    PROJECT_R_NAME: MainBlocks/BA3_ucm010_ku15_riviera
  needs: ["SIM:BA3_ucm010_ku15_questa", "RIV:BA3_ucm010_ku15_riviera"]
  
CHK:BA3_ucm010_ku15:
  extends: .sim_check
  variables: 
    extends: .vars
    PROJECT_NAME: MainBlocks/BA3_ucm010_ku15
    BLOCK: BA3_ucm010_ku15
    SIMULATOR: questa
  needs: ["RIV:BA3_ucm010_ku15_riviera"]
  artifacts:
    name: CHK_MainBlocks_BA3_ucm010_ku15
    paths:
      - $CI_PROJECT_DIR/bin
    expire_in: 30 day

