// This file was auto-generated by YML2HDL tool.
// https://gitlab.com/tcpaiva/yml2hdl
// 2022-03-15 23:42:16

`ifndef UCM_CTRL_SVH
`define UCM_CTRL_SVH


`include <common_ieee_pkg.svh>

package UCM_CTRL;

   typedef struct UCM_SUPER_ACTIONS_CTRL_t {
      logic RESET;
      logic ENABLE;
      logic DISABLE;
      logic FREEZE;
   };

   typedef struct UCM_SUPER_CONFIGS_CTRL_t {
      logic THREADS[4:0];
      logic INPUT_EN;
      logic OUTPUT_EN;
   };

   typedef struct UCM_SUPER_STATUS_MON_t {
      logic ENABLED;
      logic READY;
      logic ERROR[8:0];
   };

   typedef struct UCM_SUPER_SECTOR_PHI_MON_t {
      logic rd_data[10:0];
   };

   typedef struct UCM_SUPER_SECTOR_PHI_CTRL_t {
      logic wr_req;
      logic rd_req;
      logic wr_data[10:0];
   };

   typedef struct UCM_SUPER_CDE_CHAMB_Z0_CDE_CHAMB_Z0_SIGNALS_MON_t {
      logic rd_rdy;
      logic freeze_ena;
   };

   typedef struct UCM_SUPER_CDE_CHAMB_Z0_CDE_CHAMB_Z0_SIGNALS_CTRL_t {
      logic wr_req;
      logic wr_ack;
      logic rd_req;
      logic rd_ack;
      logic flush_req;
      logic freeze_req;
      logic mem_sel[3:0];
   };

   typedef struct UCM_SUPER_CDE_CHAMB_Z0_CDE_CHAMB_Z0_wr_data_CTRL_t {
      logic wr_data_0[16:0];
   };

   typedef struct UCM_SUPER_CDE_CHAMB_Z0_CDE_CHAMB_Z0_rd_data_MON_t {
      logic rd_data_0[16:0];
   };

   typedef struct UCM_SUPER_CDE_CHAMB_Z0_CDE_CHAMB_Z0_MON_t {
      UCM_SUPER_CDE_CHAMB_Z0_CDE_CHAMB_Z0_SIGNALS_MON_t SIGNALS;
      UCM_SUPER_CDE_CHAMB_Z0_CDE_CHAMB_Z0_rd_data_MON_t rd_data;
   };

   typedef UCM_SUPER_CDE_CHAMB_Z0_CDE_CHAMB_Z0_MON_t UCM_SUPER_CDE_CHAMB_Z0_CDE_CHAMB_Z0_MON_t_ARRAY[4:0];

   typedef struct UCM_SUPER_CDE_CHAMB_Z0_CDE_CHAMB_Z0_CTRL_t {
      UCM_SUPER_CDE_CHAMB_Z0_CDE_CHAMB_Z0_SIGNALS_CTRL_t SIGNALS;
      logic wr_addr[8:0];
      logic rd_addr[8:0];
      UCM_SUPER_CDE_CHAMB_Z0_CDE_CHAMB_Z0_wr_data_CTRL_t wr_data;
   };

   typedef UCM_SUPER_CDE_CHAMB_Z0_CDE_CHAMB_Z0_CTRL_t UCM_SUPER_CDE_CHAMB_Z0_CDE_CHAMB_Z0_CTRL_t_ARRAY[4:0];

   typedef struct UCM_SUPER_CDE_CHAMB_Z0_MON_t {
      UCM_SUPER_CDE_CHAMB_Z0_CDE_CHAMB_Z0_MON_t_ARRAY CDE_CHAMB_Z0;
   };

   typedef struct UCM_SUPER_CDE_CHAMB_Z0_CTRL_t {
      UCM_SUPER_CDE_CHAMB_Z0_CDE_CHAMB_Z0_CTRL_t_ARRAY CDE_CHAMB_Z0;
   };

   typedef struct UCM_SUPER_CVP_CHAMB_Z0_CVP_CHAMB_Z0_SIGNALS_MON_t {
      logic rd_rdy;
      logic freeze_ena;
   };

   typedef struct UCM_SUPER_CVP_CHAMB_Z0_CVP_CHAMB_Z0_SIGNALS_CTRL_t {
      logic wr_req;
      logic wr_ack;
      logic rd_req;
      logic rd_ack;
      logic flush_req;
      logic freeze_req;
      logic mem_sel[3:0];
   };

   typedef struct UCM_SUPER_CVP_CHAMB_Z0_CVP_CHAMB_Z0_wr_data_CTRL_t {
      logic wr_data_0[16:0];
   };

   typedef struct UCM_SUPER_CVP_CHAMB_Z0_CVP_CHAMB_Z0_rd_data_MON_t {
      logic rd_data_0[16:0];
   };

   typedef struct UCM_SUPER_CVP_CHAMB_Z0_CVP_CHAMB_Z0_MON_t {
      UCM_SUPER_CVP_CHAMB_Z0_CVP_CHAMB_Z0_SIGNALS_MON_t SIGNALS;
      UCM_SUPER_CVP_CHAMB_Z0_CVP_CHAMB_Z0_rd_data_MON_t rd_data;
   };

   typedef UCM_SUPER_CVP_CHAMB_Z0_CVP_CHAMB_Z0_MON_t UCM_SUPER_CVP_CHAMB_Z0_CVP_CHAMB_Z0_MON_t_ARRAY[4:0];

   typedef struct UCM_SUPER_CVP_CHAMB_Z0_CVP_CHAMB_Z0_CTRL_t {
      UCM_SUPER_CVP_CHAMB_Z0_CVP_CHAMB_Z0_SIGNALS_CTRL_t SIGNALS;
      logic wr_addr[8:0];
      logic rd_addr[8:0];
      UCM_SUPER_CVP_CHAMB_Z0_CVP_CHAMB_Z0_wr_data_CTRL_t wr_data;
   };

   typedef UCM_SUPER_CVP_CHAMB_Z0_CVP_CHAMB_Z0_CTRL_t UCM_SUPER_CVP_CHAMB_Z0_CVP_CHAMB_Z0_CTRL_t_ARRAY[4:0];

   typedef struct UCM_SUPER_CVP_CHAMB_Z0_MON_t {
      UCM_SUPER_CVP_CHAMB_Z0_CVP_CHAMB_Z0_MON_t_ARRAY CVP_CHAMB_Z0;
   };

   typedef struct UCM_SUPER_CVP_CHAMB_Z0_CTRL_t {
      UCM_SUPER_CVP_CHAMB_Z0_CVP_CHAMB_Z0_CTRL_t_ARRAY CVP_CHAMB_Z0;
   };

   typedef struct UCM_SUPER_MON_t {
      UCM_SUPER_STATUS_MON_t STATUS;
      UCM_SUPER_SECTOR_PHI_MON_t SECTOR_PHI;
      UCM_SUPER_CDE_CHAMB_Z0_MON_t CDE_CHAMB_Z0;
      UCM_SUPER_CVP_CHAMB_Z0_MON_t CVP_CHAMB_Z0;
   };

   typedef struct UCM_SUPER_CTRL_t {
      UCM_SUPER_ACTIONS_CTRL_t ACTIONS;
      UCM_SUPER_CONFIGS_CTRL_t CONFIGS;
      UCM_SUPER_SECTOR_PHI_CTRL_t SECTOR_PHI;
      UCM_SUPER_CDE_CHAMB_Z0_CTRL_t CDE_CHAMB_Z0;
      UCM_SUPER_CVP_CHAMB_Z0_CTRL_t CVP_CHAMB_Z0;
   };

   typedef struct UCM_R_PHI_COMP_RPC_MEM_INTERFACE_MON_t {
      logic rd_rdy;
      logic rd_data[12:0];
   };

   typedef struct UCM_R_PHI_COMP_RPC_MEM_INTERFACE_CTRL_t {
      logic wr_req;
      logic rd_req;
      logic wr_addr[5:0];
      logic rd_addr[5:0];
      logic wr_data[12:0];
   };

   typedef struct UCM_R_PHI_COMP_RPC_MON_t {
      UCM_R_PHI_COMP_RPC_MEM_INTERFACE_MON_t MEM_INTERFACE;
   };

   typedef struct UCM_R_PHI_COMP_RPC_CTRL_t {
      logic sel_thread[4:0];
      logic sel_station[4:0];
      logic sel_layer[4:0];
      logic ext_ctrl;
      UCM_R_PHI_COMP_RPC_MEM_INTERFACE_CTRL_t MEM_INTERFACE;
   };

   typedef struct UCM_R_PHI_COMP_MDT_MEM_INTERFACE_MON_t {
      logic rd_rdy;
      logic rd_data[14:0];
   };

   typedef struct UCM_R_PHI_COMP_MDT_MEM_INTERFACE_CTRL_t {
      logic wr_req;
      logic rd_req;
      logic wr_addr[5:0];
      logic rd_addr[5:0];
      logic wr_data[14:0];
   };

   typedef struct UCM_R_PHI_COMP_MDT_MON_t {
      UCM_R_PHI_COMP_MDT_MEM_INTERFACE_MON_t MEM_INTERFACE;
   };

   typedef struct UCM_R_PHI_COMP_MDT_CTRL_t {
      logic sel_thread[4:0];
      logic sel_station[4:0];
      logic sel_layer[4:0];
      logic ext_ctrl;
      UCM_R_PHI_COMP_MDT_MEM_INTERFACE_CTRL_t MEM_INTERFACE;
   };

   typedef struct UCM_R_PHI_COMP_MON_t {
      UCM_R_PHI_COMP_RPC_MON_t RPC;
      UCM_R_PHI_COMP_MDT_MON_t MDT;
   };

   typedef struct UCM_R_PHI_COMP_CTRL_t {
      UCM_R_PHI_COMP_RPC_CTRL_t RPC;
      UCM_R_PHI_COMP_MDT_CTRL_t MDT;
   };

   typedef struct UCM_MON_t {
      UCM_SUPER_MON_t SUPER;
      UCM_R_PHI_COMP_MON_t R_PHI_COMP;
   };

   typedef struct UCM_CTRL_t {
      UCM_SUPER_CTRL_t SUPER;
      UCM_R_PHI_COMP_CTRL_t R_PHI_COMP;
   };

endpackage : UCM_CTRL

`endif // UCM_CTRL_SVH
