#################### ult_tp_dev Project ###########################
GEN:ult_tp_dev:
    extends: .GEN
    variables:
      extends: .vars
      PROJECT_NAME: ult_tp_dev
      HOG_ONLY_SYNTH: 1 # if 1 runs only the synthesis

SIM:ult_tp_dev:
    extends: .SIM
    variables:
      extends: .vars
      PROJECT_NAME: ult_tp_dev
    allow_failure: false

# sim_comp:ult_tp_dev:
#     extends: .sim_comp
#     variables:
#       extends: .vars
#       PROJECT_NAME: ult_tp_dev

