# #################### CSF Project ###########################

generate_project:csf:
    extends: .create_project
    variables:
      extends: .vars
      PROJECT_NAME: csf

# simulate_project:csf:
#     extends: .simulate_project
#     variables:
#       extends: .vars
#       PROJECT_NAME: csf
