# cp
cp /tmp/my-sector-logic-gty-interface/proj/gty_fixed_latency_ex/imports/gty_fixed_latency_example_top.v .
cp /tmp/my-sector-logic-gty-interface/proj/gty_fixed_latency_ex/imports/gty_fixed_latency_example_init.v .
cp /tmp/my-sector-logic-gty-interface/proj/gty_fixed_latency_ex/imports/gty_fixed_latency_example_wrapper.v .
cp /tmp/my-sector-logic-gty-interface/proj/gty_fixed_latency_ex/imports/gty_fixed_latency_example_reset_sync.v .
cp /tmp/my-sector-logic-gty-interface/proj/gty_fixed_latency_ex/imports/gty_fixed_latency_example_bit_sync.v .
cp /tmp/my-sector-logic-gty-interface/proj/gty_fixed_latency_ex/imports/gty_fixed_latency_example_gtwiz_userclk_rx.v .
cp /tmp/my-sector-logic-gty-interface/proj/gty_fixed_latency_ex/imports/gty_fixed_latency_example_gtwiz_userclk_tx.v .
cp /tmp/my-sector-logic-gty-interface/proj/gty_fixed_latency_ex/imports/gty_fixed_latency_example_gtwiz_userdata_rx.v .
cp /tmp/my-sector-logic-gty-interface/proj/gty_fixed_latency_ex/imports/gty_fixed_latency_example_gtwiz_userdata_tx.v .
cp /tmp/my-sector-logic-gty-interface/proj/gty_fixed_latency_ex/imports/gty_fixed_latency_example_gtwiz_reset.v .
cp /tmp/my-sector-logic-gty-interface/proj/gty_fixed_latency_ex/imports/gty_fixed_latency_gtye4_common_wrapper.v .
cp /tmp/my-sector-logic-gty-interface/proj/gty_fixed_latency_ex/imports/gtwizard_ultrascale_v1_7_gtye4_common.v .
cp /tmp/my-sector-logic-gty-interface/proj/gty_fixed_latency_ex/gty_fixed_latency_ex.srcs/sources_1/ip/gty_fixed_latency/synth/gty_fixed_latency.v .
cp /tmp/my-sector-logic-gty-interface/proj/gty_fixed_latency_ex/gty_fixed_latency_ex.srcs/sources_1/ip/gty_fixed_latency/synth/gty_fixed_latency_gtwizard_top.v .
cp /tmp/my-sector-logic-gty-interface/proj/gty_fixed_latency_ex/gty_fixed_latency_ex.srcs/sources_1/ip/gty_fixed_latency/synth/gty_fixed_latency_gtwizard_gtye4.v .
cp /tmp/my-sector-logic-gty-interface/proj/gty_fixed_latency_ex/gty_fixed_latency_ex.srcs/sources_1/ip/gty_fixed_latency/synth/gty_fixed_latency_gtye4_channel_wrapper.v .
cp /tmp/my-sector-logic-gty-interface/proj/gty_fixed_latency_ex/gty_fixed_latency_ex.srcs/sources_1/ip/gty_fixed_latency/synth/gtwizard_ultrascale_v1_7_gtye4_channel.v .
cp /tmp/my-sector-logic-gty-interface/proj/gty_fixed_latency_ex/gty_fixed_latency_ex.srcs/sources_1/ip/gty_fixed_latency/hdl/gtwizard_ultrascale_v1_7_gtye4_cpll_cal.v .
cp /tmp/my-sector-logic-gty-interface/proj/gty_fixed_latency_ex/gty_fixed_latency_ex.srcs/sources_1/ip/gty_fixed_latency/hdl/gtwizard_ultrascale_v1_7_reset_sync.v .
cp /tmp/my-sector-logic-gty-interface/proj/gty_fixed_latency_ex/gty_fixed_latency_ex.srcs/sources_1/ip/gty_fixed_latency/hdl/gtwizard_ultrascale_v1_7_bit_sync.v .
cp /tmp/my-sector-logic-gty-interface/proj/gty_fixed_latency_ex/gty_fixed_latency_ex.srcs/sources_1/ip/gty_fixed_latency/hdl/gtwizard_ultrascale_v1_7_gtye4_cal_freqcnt.v .
cp /tmp/my-sector-logic-gty-interface/proj/gty_fixed_latency_ex/gty_fixed_latency_ex.srcs/sources_1/ip/gty_fixed_latency/hdl/gtwizard_ultrascale_v1_7_gte4_drp_arb.v .
cp /tmp/my-sector-logic-gty-interface/proj/gty_fixed_latency_ex/gty_fixed_latency_ex.srcs/sources_1/ip/gty_fixed_latency/hdl/gtwizard_ultrascale_v1_7_gthe4_cal_freqcnt.v .
cp /tmp/my-sector-logic-gty-interface/proj/gty_fixed_latency_ex/gty_fixed_latency_ex.srcs/sources_1/ip/gty_fixed_latency/hdl/gtwizard_ultrascale_v1_7_gthe4_cpll_cal.v .
cp /tmp/my-sector-logic-gty-interface/proj/gty_fixed_latency_ex/gty_fixed_latency_ex.srcs/sources_1/ip/gty_fixed_latency/hdl/gtwizard_ultrascale_v1_7_gthe4_cpll_cal_rx.v .
cp /tmp/my-sector-logic-gty-interface/proj/gty_fixed_latency_ex/gty_fixed_latency_ex.srcs/sources_1/ip/gty_fixed_latency/hdl/gtwizard_ultrascale_v1_7_gthe4_cpll_cal_tx.v .
cp /tmp/my-sector-logic-gty-interface/proj/gty_fixed_latency_ex/gty_fixed_latency_ex.srcs/sources_1/ip/gty_fixed_latency/hdl/gtwizard_ultrascale_v1_7_gthe4_delay_powergood.v .
cp /tmp/my-sector-logic-gty-interface/proj/gty_fixed_latency_ex/gty_fixed_latency_ex.srcs/sources_1/ip/gty_fixed_latency/hdl/gtwizard_ultrascale_v1_7_gtwiz_buffbypass_rx.v .
cp /tmp/my-sector-logic-gty-interface/proj/gty_fixed_latency_ex/gty_fixed_latency_ex.srcs/sources_1/ip/gty_fixed_latency/hdl/gtwizard_ultrascale_v1_7_gtwiz_buffbypass_tx.v .
cp /tmp/my-sector-logic-gty-interface/proj/gty_fixed_latency_ex/gty_fixed_latency_ex.srcs/sources_1/ip/gty_fixed_latency/hdl/gtwizard_ultrascale_v1_7_gtwiz_reset.v .
cp /tmp/my-sector-logic-gty-interface/proj/gty_fixed_latency_ex/gty_fixed_latency_ex.srcs/sources_1/ip/gty_fixed_latency/hdl/gtwizard_ultrascale_v1_7_gtwiz_userclk_rx.v .
cp /tmp/my-sector-logic-gty-interface/proj/gty_fixed_latency_ex/gty_fixed_latency_ex.srcs/sources_1/ip/gty_fixed_latency/hdl/gtwizard_ultrascale_v1_7_gtwiz_userclk_tx.v .
cp /tmp/my-sector-logic-gty-interface/proj/gty_fixed_latency_ex/gty_fixed_latency_ex.srcs/sources_1/ip/gty_fixed_latency/hdl/gtwizard_ultrascale_v1_7_gtwiz_userdata_rx.v .
cp /tmp/my-sector-logic-gty-interface/proj/gty_fixed_latency_ex/gty_fixed_latency_ex.srcs/sources_1/ip/gty_fixed_latency/hdl/gtwizard_ultrascale_v1_7_gtwiz_userdata_tx.v .
cp /tmp/my-sector-logic-gty-interface/proj/gty_fixed_latency_ex/gty_fixed_latency_ex.srcs/sources_1/ip/gty_fixed_latency/hdl/gtwizard_ultrascale_v1_7_gtye4_cal_freqcnt.v .
cp /tmp/my-sector-logic-gty-interface/proj/gty_fixed_latency_ex/gty_fixed_latency_ex.srcs/sources_1/ip/gty_fixed_latency/hdl/gtwizard_ultrascale_v1_7_gtye4_cpll_cal.v .
cp /tmp/my-sector-logic-gty-interface/proj/gty_fixed_latency_ex/gty_fixed_latency_ex.srcs/sources_1/ip/gty_fixed_latency/hdl/gtwizard_ultrascale_v1_7_gtye4_cpll_cal_rx.v .
cp /tmp/my-sector-logic-gty-interface/proj/gty_fixed_latency_ex/gty_fixed_latency_ex.srcs/sources_1/ip/gty_fixed_latency/hdl/gtwizard_ultrascale_v1_7_gtye4_cpll_cal_tx.v .
cp /tmp/my-sector-logic-gty-interface/proj/gty_fixed_latency_ex/gty_fixed_latency_ex.srcs/sources_1/ip/gty_fixed_latency/hdl/gtwizard_ultrascale_v1_7_gtye4_delay_powergood.v .
cp /tmp/my-sector-logic-gty-interface/proj/gty_fixed_latency_ex/gty_fixed_latency_ex.srcs/sources_1/ip/gty_fixed_latency/hdl/gtwizard_ultrascale_v1_7_reset_inv_sync.v .
cp /tmp/my-sector-logic-gty-interface/proj/gty_fixed_latency_ex/imports/gty_fixed_latency_example_wrapper_functions.v .
cp /tmp/my-sector-logic-gty-interface/proj/gty_fixed_latency_ex/imports/gty_fixed_latency_example_reset_inv_sync.v .
cp /tmp/my-sector-logic-gty-interface/proj/gty_fixed_latency_ex/imports/gty_fixed_latency_example_gtwiz_buffbypass_tx.v ./
cp /tmp/my-sector-logic-gty-interface/proj/gty_fixed_latency_ex/imports/gty_fixed_latency_example_gtwiz_buffbypass_rx.v ./

