#################### l0mdt Project ###########################
GEN:l0mdt_ku15p_ull_fm:
    extends: .generate_project
    variables:
      extends: .vars
      PROJECT_NAME: l0mdt_ku15p_ull_fm
      HOG_ONLY_SYNTH: 0 # if 1 runs only the synthesis
      HOG_CHECK_SYNTAX: 0
      HOG_NO_BITSTREAM: 0 
    tags:
      - mdt-1
    artifacts:
      when: always
        name: implementation_and_bitfiles
        paths:
          - bin 
      when: on_failure
        paths:
          - Projects


