#################### tf1 Project ###########################

create_project:tf1:
    extends: .create_project
    variables:
      extends: .vars
      PROJECT_NAME: tf1

simulate_project:tf1:
    extends: .simulate_project
    variables:
      extends: .vars
      PROJECT_NAME: tf1

synthesise_ips:tf1:
    extends: .synthesise_ips
    variables:
      extends: .vars
      PROJECT_NAME: tf1
      IP_PATH: IP
    dependencies:
        - create_project:tf1

synthesise_project:tf1:
    extends: .synthesise_project
    variables:
      extends: .vars
      PROJECT_NAME: tf1
    dependencies:
        - synthesise_ips:tf1
        - create_project:tf1

# implement_project:tf1:
#     extends: .implement_project
#     variables:
#       extends: .vars
#       PROJECT_NAME: tf1
#     dependencies:
#        - create_project:tf1
#        - synthesise_ips:tf1
#        - synthesise_project:tf1

