#################### l0mdt Project ###########################
GEN:l0mdt_vu13p_ba3_ucm_mpl_tar_hps:
    extends: .generate_project
    variables:
      extends: .vars
      PROJECT_NAME: l0mdt_vu13p_ba3_ucm_mpl_tar_hps
      HOG_ONLY_SYNTH: 0 # if 1 runs only the synthesis
      HOG_CHECK_SYNTAX: 0
      HOG_NO_BITSTREAM: 1 
    tags:
      - argos
