
all:
	python3.7 ../../../l0mdt-custom-types/yml2hdl.py -e ../config/config_type.yml common.yml
	python3.7 ../../../l0mdt-custom-types/yml2hdl.py -e ../config/config_type.yml -e common.yml ../../ucm/pkg/ucm.yml
	python3.7 ../../../l0mdt-custom-types/yml2hdl.py -e ../config/config_type.yml -e common.yml ../../hp/pkg/hp.yml
	# python3.7 ../../../l0mdt-custom-types/yml2hdl.py -e ../config/config_type.yml -e common.yml -e ../../hp/pkg/hp.yml ../../heg/pkg/heg.yml
