# set_property AUTO_INCREMENTAL_CHECKPOINT 1 [get_runs impl_1]
# set_property AUTO_INCREMENTAL_CHECKPOINT 1 [get_runs synth_1]
# set_property -name {riviera.compile.vhdl_relax} -value {true} -objects [get_filesets project_lib]
# set_property -name {riviera.compile.vhdl_syntax} -value {2008} -objects [get_filesets project_lib]
current_fileset -simset [ get_filesets project_lib ]
set_property generic g_STATION=2 [current_fileset]