#################### hp Project ###########################
generate_project:hp:
    extends: .generate_project
    variables:
      extends: .vars
      PROJECT_NAME: hp
      HOG_ONLY_SYNTH: 1 # if 1 runs only the synthesis

# simulate_project:hp:
#     extends: .simulate_project
#     variables:
#       extends: .vars
#       PROJECT_NAME: hp
