#################### tar.0 Project ###########################
GEN:tar.0:
    extends: .generate_project
    variables:
      extends: .vars
      PROJECT_NAME: MainBlocks/tar.0
      HOG_ONLY_SYNTH: 0 # if 1 runs only the synthesis
      
    tags:
      - normal-ops
      - hog
      # - "2020.2"


# SIM:tar.0_vivado:
#     extends: .simulate_project
#     variables:
#       extends: .vars
#       PROJECT_NAME: MainBlocks/tar.0

SIM:tar.0_questa:
    extends: .simulate_project
    variables:
      extends: .vars
      PROJECT_NAME: MainBlocks/tar.0

SIM:tar.0_riviera:
    extends: .riviera_sim
    variables:
      extends: .vars
      PROJECT_NAME: MainBlocks/tar.0
    # allow_failure: false

COMP:tar.0:
  extends: .sim_comp
  variables:
    extends: .vars
    PROJECT_NAME: MainBlocks/tar.0
    PROJECT_Q_NAME: MainBlocks/tar.0_questa
    PROJECT_R_NAME: MainBlocks/tar.0_riviera
  needs: ["SIM:tar.0_questa","SIM:tar.0_riviera"]

CHK:tar.0:
  extends: .sim_check
  variables: 
    extends: .vars
    PROJECT_NAME: MainBlocks/tar.0
    BLOCK: tar.0
    SIMULATOR: questa
  needs: ["SIM:tar.0_riviera"]
  artifacts:
    name: CHK_MainBlocks_tar.0
    paths:
      - $CI_PROJECT_DIR/bin
    expire_in: 30 day
