#################### ult Project ###########################
generate_project:ult:
    extends: .generate_project
    variables:
      extends: .vars
      PROJECT_NAME: ult
      HOG_ONLY_SYNTH: 1 # if 1 runs only the synthesis

# simulate_project:ult:
#     extends: .simulate_project
#     variables:
#       extends: .vars
#       PROJECT_NAME: ult
