#################### ult Project ###########################
GEN:ult:
    extends: .GEN
    variables:
      extends: .vars
      PROJECT_NAME: ult
      HOG_ONLY_SYNTH: 1 # if 1 runs only the synthesis

# SIM:ult:
#     extends: .SIM
#     variables:
#       extends: .vars
#       PROJECT_NAME: ult
