// This file was auto-generated by YML2HDL toll.
// https://gitlab.com/tcpaiva/yml2hdl

`ifndef TTC_DEFS_SVH
`define TTC_DEFS_SVH

`include <common_defs.svh>


  typedef logic  clk_t;

  typedef bcid_t   bcid_at;

  typedef logic unsigned [32-1:0] evid_t;

  typedef logic unsigned [32-1:0] orid_t;

  typedef struct packed {
    logic  clk40;
    logic  clk320;
    logic  rst;
  } ttc_sys_rt;

  typedef struct packed {
    logic  bcr;
    logic  ecr;
    logic  lxa;
    logic  reserved0;
    logic  reserved1;
    logic  reserved2;
    logic  reserved3;
    logic  reserved4;
  } ttc_fmt_rt;

  // ttc_fmt_vt: 40MHz domain
  typedef logic [$bits(ttc_fmt_rt)-1:0] ttc_fmt_vt;

  // ttc_cmds_rt:
  // 320MHz domain
  typedef struct packed {
    logic  bcr;
    logic  ocr;
    logic  ecr;
    logic  lxa;
    logic  bx;
  } ttc_cmds_rt;

  typedef struct packed {
    bcid_t   bcid;
    evid_t   evid;
    orid_t   orid;
  } ttc_counters_rt;

  typedef struct packed {
    ttc_sys_rt   sys;
    ttc_fmt_vt   data;
  } ttc_irt;

  typedef logic [$bits(ttc_irt)-1:0] ttc_ivt;

  typedef struct packed {
    ttc_cmds_rt   cmds;
    ttc_counters_rt   cnt;
  } ttc_ort;

  typedef logic [$bits(ttc_ort)-1:0] ttc_ovt;

  typedef struct packed {
    ttc_irt   i;
    ttc_ort   o;
  } ttc_ert;



`endif // TTC_DEFS_SVH
