set_false_path -from [get_clocks -of_objects [get_pins top_hal/top_clocking_inst/Clocking_inst/inst/mmcme4_adv_inst/CLKOUT2]] -to [get_clocks -of_objects [get_pins {top_hal/mgt_wrapper_inst/mgt_gen[8].sl_gen.MGT_INST/gty_gen.MGT_GEN/example_wrapper_inst/gty_fixed_latency_inst/inst/gen_gtwizard_gtye4_top.gty_fixed_latency_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_channel_container[2].gen_enabled_channel.gtye4_channel_wrapper_inst/channel_inst/gtye4_channel_gen.gen_gtye4_channel_inst[3].GTYE4_CHANNEL_PRIM_INST/TXOUTCLK}]]
set_false_path -from [get_clocks -of_objects [get_pins top_hal/top_clocking_inst/Clocking_inst/inst/mmcme4_adv_inst/CLKOUT2]] -to [get_clocks -of_objects [get_pins {top_hal/mgt_wrapper_inst/mgt_gen[8].sl_gen.MGT_INST/gty_gen.MGT_GEN/example_wrapper_inst/gty_fixed_latency_inst/inst/gen_gtwizard_gtye4_top.gty_fixed_latency_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_channel_container[2].gen_enabled_channel.gtye4_channel_wrapper_inst/channel_inst/gtye4_channel_gen.gen_gtye4_channel_inst[3].GTYE4_CHANNEL_PRIM_INST/RXOUTCLK}]]
set_false_path -from [get_pins {top_hal/mgt_wrapper_inst/mgt_gen[8].sl_gen.MGT_INST/gty_gen.MGT_GEN/example_wrapper_inst/gtwiz_reset_inst/reset_synchronizer_rx_done_inst/rst_in_out_reg/C}] -to [get_pins {top_hal/mgt_wrapper_inst/mgt_gen[8].sl_gen.MGT_INST/gty_gen.MGT_GEN/example_init_inst/bit_synchronizer_rx_init_done_inst/i_in_meta_reg/D}]
set_false_path -from [get_clocks -of_objects [get_pins {top_hal/mgt_wrapper_inst/mgt_gen[8].sl_gen.MGT_INST/gty_gen.MGT_GEN/example_wrapper_inst/gty_fixed_latency_inst/inst/gen_gtwizard_gtye4_top.gty_fixed_latency_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_channel_container[2].gen_enabled_channel.gtye4_channel_wrapper_inst/channel_inst/gtye4_channel_gen.gen_gtye4_channel_inst[*].GTYE4_CHANNEL_PRIM_INST/TXOUTCLKPCS}]] -to [get_clocks -of_objects [get_pins top_hal/top_clocking_inst/Clocking_inst/inst/mmcme4_adv_inst/CLKOUT2]]
set_false_path -from [get_clocks -of_objects [get_pins {top_hal/mgt_wrapper_inst/mgt_gen[8].sl_gen.MGT_INST/gty_gen.MGT_GEN/example_wrapper_inst/gty_fixed_latency_inst/inst/gen_gtwizard_gtye4_top.gty_fixed_latency_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_channel_container[2].gen_enabled_channel.gtye4_channel_wrapper_inst/channel_inst/gtye4_channel_gen.gen_gtye4_channel_inst[2].GTYE4_CHANNEL_PRIM_INST/TXOUTCLKPCS}]] -to [get_clocks -of_objects [get_pins top_hal/top_clocking_inst/Clocking_inst/inst/mmcme4_adv_inst/CLKOUT2]]
set_false_path -from [get_clocks -of_objects [get_pins {top_hal/mgt_wrapper_inst/mgt_gen[8].sl_gen.MGT_INST/gty_gen.MGT_GEN/example_wrapper_inst/gty_fixed_latency_inst/inst/gen_gtwizard_gtye4_top.gty_fixed_latency_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_channel_container[2].gen_enabled_channel.gtye4_channel_wrapper_inst/channel_inst/gtye4_channel_gen.gen_gtye4_channel_inst[3].GTYE4_CHANNEL_PRIM_INST/TXOUTCLK}]] -to [get_clocks -of_objects [get_pins top_hal/top_clocking_inst/Clocking_inst/inst/mmcme4_adv_inst/CLKOUT2]]
set_false_path -from [get_pins {top_hal/mgt_wrapper_inst/mgt_gen[8].sl_gen.MGT_INST/gty_gen.MGT_GEN/example_wrapper_inst/gty_fixed_latency_inst/inst/gen_gtwizard_gtye4_top.gty_fixed_latency_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_channel_container[2].gen_enabled_channel.gtye4_channel_wrapper_inst/channel_inst/gtye4_channel_gen.gen_gtye4_channel_inst[1].GTYE4_CHANNEL_PRIM_INST/RXUSRCLK2}] -to [get_pins {top_hal/mgt_wrapper_inst/mgt_gen[8].sl_gen.MGT_INST/gty_gen.MGT_GEN/example_wrapper_inst/gen_ch_xrd[1].bit_synchronizer_rxresetdone_inst/i_in_meta_reg/D}]
set_false_path -from [get_pins {top_hal/mgt_wrapper_inst/mgt_gen[8].sl_gen.MGT_INST/gty_gen.MGT_GEN/example_wrapper_inst/gen_gtwiz_buffbypass_rx[1].gtwiz_buffbypass_rx_inst/gen_gtwiz_buffbypass_rx_main.gen_auto_mode.gtwiz_buffbypass_rx_done_out_reg/C}] -to [get_pins {top_hal/mgt_wrapper_inst/mgt_gen[8].sl_gen.MGT_INST/gty_gen.MGT_GEN/example_init_inst/bit_synchronizer_rx_init_done_inst/i_in_meta_reg/D}]
set_false_path -from [get_clocks -of_objects [get_pins {top_hal/mgt_wrapper_inst/mgt_gen[8].sl_gen.MGT_INST/gty_gen.MGT_GEN/example_wrapper_inst/gty_fixed_latency_inst/inst/gen_gtwizard_gtye4_top.gty_fixed_latency_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_channel_container[2].gen_enabled_channel.gtye4_channel_wrapper_inst/channel_inst/gtye4_channel_gen.gen_gtye4_channel_inst[2].GTYE4_CHANNEL_PRIM_INST/RXOUTCLK}]] -to [get_clocks -of_objects [get_pins top_hal/top_clocking_inst/Clocking_inst/inst/mmcme4_adv_inst/CLKOUT2]]


#FIX mgt_wrapper.vhd line ~205 -> double buffer registers crossing clock domains and then add relevant false path constraints
set_false_path -from [get_clocks -of_objects [get_pins {top_hal/mgt_wrapper_inst/mgt_gen[8].sl_gen.MGT_INST/gty_gen.MGT_GEN/example_wrapper_inst/gty_fixed_latency_inst/inst/gen_gtwizard_gtye4_top.gty_fixed_latency_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_channel_container[2].gen_enabled_channel.gtye4_channel_wrapper_inst/channel_inst/gtye4_channel_gen.gen_gtye4_channel_inst[0].GTYE4_CHANNEL_PRIM_INST/TXOUTCLKPCS}]] -to [get_clocks -of_objects [get_pins top_hal/top_clocking_inst/Clocking_inst/inst/mmcme4_adv_inst/CLKOUT1]]
set_false_path -from [get_clocks -of_objects [get_pins {top_hal/mgt_wrapper_inst/mgt_gen[8].sl_gen.MGT_INST/gty_gen.MGT_GEN/example_wrapper_inst/gty_fixed_latency_inst/inst/gen_gtwizard_gtye4_top.gty_fixed_latency_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_channel_container[2].gen_enabled_channel.gtye4_channel_wrapper_inst/channel_inst/gtye4_channel_gen.gen_gtye4_channel_inst[1].GTYE4_CHANNEL_PRIM_INST/TXOUTCLKPCS}]] -to [get_clocks -of_objects [get_pins top_hal/top_clocking_inst/Clocking_inst/inst/mmcme4_adv_inst/CLKOUT1]]
set_false_path -from [get_clocks -of_objects [get_pins {top_hal/mgt_wrapper_inst/mgt_gen[8].sl_gen.MGT_INST/gty_gen.MGT_GEN/example_wrapper_inst/gty_fixed_latency_inst/inst/gen_gtwizard_gtye4_top.gty_fixed_latency_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_channel_container[2].gen_enabled_channel.gtye4_channel_wrapper_inst/channel_inst/gtye4_channel_gen.gen_gtye4_channel_inst[2].GTYE4_CHANNEL_PRIM_INST/TXOUTCLKPCS}]] -to [get_clocks -of_objects [get_pins top_hal/top_clocking_inst/Clocking_inst/inst/mmcme4_adv_inst/CLKOUT1]]
set_false_path -from [get_clocks -of_objects [get_pins {top_hal/mgt_wrapper_inst/mgt_gen[8].sl_gen.MGT_INST/gty_gen.MGT_GEN/example_wrapper_inst/gty_fixed_latency_inst/inst/gen_gtwizard_gtye4_top.gty_fixed_latency_gtwizard_gtye4_inst/gen_gtwizard_gtye4.gen_channel_container[2].gen_enabled_channel.gtye4_channel_wrapper_inst/channel_inst/gtye4_channel_gen.gen_gtye4_channel_inst[3].GTYE4_CHANNEL_PRIM_INST/TXOUTCLKPCS}]] -to [get_clocks -of_objects [get_pins top_hal/top_clocking_inst/Clocking_inst/inst/mmcme4_adv_inst/CLKOUT1]]

set_false_path -from [get_clocks *GTYE4_CHANNEL_RXOUTCLK*] -to [get_clocks -of_objects [get_pins top_hal/top_clocking_inst/Clocking_inst/inst/mmcme4_adv_inst/CLKOUT2]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets axi_clk]
