#vivado
[main]
BIN_FILE = 1
FPGA = xcku15p-ffva1760-2-e
SYNTH_STRATEGY = "Flow_AreaOptimized_High" 
SYNTH_FLOW = "Vivado Synthesis 2019"
IMPL_STRATEGY = "Performance_ExplorePostRoutePhysOpt"
IMPL_FLOW = "Vivado Implementation 2019"

[synth_1]
STEPS.SYNTH_DESIGN.ARGS.FANOUT_LIMIT = 600
STEPS.SYNTH_DESIGN.ARGS.RETIMING =  true 

[impl_1]
STEPS.OPT_DESIGN.ARGS.DIRECTIVE = Default
STEPS.POST_ROUTE_PHYS_OPT_DESIGN.ARGS.DIRECTIVE = AggressiveExplore
