#################### ull_vu13_b3a_tar Project ###########################
GEN:ull_vu13_b3a_tar:
    extends: .generate_project
    variables:
      extends: .vars
      PROJECT_NAME: ull_vu13_b3a_tar
      HOG_ONLY_SYNTH: 1 # if 1 runs only the synthesis
      
    tags:
      - heavy-duty
      - hog

SIM:ull_vu13_b3a_tar:
    extends: .simulate_project
    variables:
      extends: .vars
      PROJECT_NAME: ull_vu13_b3a_tar
      HOG_CHECK_PROJVER: 0
    before_script:
      - export PATH="/opt/Xilinx/Vivado/2019.2/bin:/opt/questa/2019.4_4/questasim/linux_x86_64:$PATH"
    tags:
      - questa
      - hog
      
      
# user_sim:ull_vu13_b3a_tar:
#     extends: .user_sim
#     variables:
#       extends: .vars
#       PROJECT_NAME: ull_vu13_b3a_tar
