onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /ult_tb/ULT/clock_and_control
add wave -noupdate /ult_tb/ULT/ttc_commands
add wave -noupdate /ult_tb/ULT/h2s_ctrl
add wave -noupdate /ult_tb/ULT/h2s_mon
add wave -noupdate /ult_tb/ULT/tar_ctrl
add wave -noupdate /ult_tb/ULT/tar_mon
add wave -noupdate /ult_tb/ULT/mtc_ctrl
add wave -noupdate /ult_tb/ULT/mtc_mon
add wave -noupdate /ult_tb/ULT/ucm_ctrl
add wave -noupdate /ult_tb/ULT/ucm_mon
add wave -noupdate /ult_tb/ULT/daq_ctrl
add wave -noupdate /ult_tb/ULT/daq_mon
add wave -noupdate /ult_tb/ULT/tf_ctrl
add wave -noupdate /ult_tb/ULT/tf_mon
add wave -noupdate /ult_tb/ULT/mpl_ctrl
add wave -noupdate /ult_tb/ULT/mpl_mon
add wave -noupdate /ult_tb/ULT/i_inner_tdc_hits
add wave -noupdate /ult_tb/ULT/i_middle_tdc_hits
add wave -noupdate /ult_tb/ULT/i_outer_tdc_hits
add wave -noupdate /ult_tb/ULT/i_extra_tdc_hits
add wave -noupdate /ult_tb/ULT/i_inner_tar_hits
add wave -noupdate /ult_tb/ULT/i_middle_tar_hits
add wave -noupdate /ult_tb/ULT/i_outer_tar_hits
add wave -noupdate /ult_tb/ULT/i_extra_tar_hits
add wave -noupdate /ult_tb/ULT/i_main_primary_slc
add wave -noupdate /ult_tb/ULT/i_main_secondary_slc
add wave -noupdate /ult_tb/ULT/i_plus_neighbor_slc
add wave -noupdate /ult_tb/ULT/i_minus_neighbor_slc
add wave -noupdate /ult_tb/ULT/i_plus_neighbor_segments
add wave -noupdate /ult_tb/ULT/i_minus_neighbor_segments
add wave -noupdate /ult_tb/ULT/o_daq_streams
add wave -noupdate /ult_tb/ULT/o_plus_neighbor_segments
add wave -noupdate /ult_tb/ULT/o_minus_neighbor_segments
add wave -noupdate /ult_tb/ULT/o_MTC
add wave -noupdate /ult_tb/ULT/o_NSP
add wave -noupdate /ult_tb/ULT/sump
add wave -noupdate /ult_tb/ULT/inner_slc_to_hts
add wave -noupdate /ult_tb/ULT/middle_slc_to_hts
add wave -noupdate /ult_tb/ULT/outer_slc_to_hts
add wave -noupdate /ult_tb/ULT/extra_slc_to_hts
add wave -noupdate /ult_tb/ULT/ucm2pl_av
add wave -noupdate /ult_tb/ULT/inner_tar_hits
add wave -noupdate /ult_tb/ULT/middle_tar_hits
add wave -noupdate /ult_tb/ULT/outer_tar_hits
add wave -noupdate /ult_tb/ULT/extra_tar_hits
add wave -noupdate /ult_tb/ULT/inner_tdc_hits
add wave -noupdate /ult_tb/ULT/middle_tdc_hits
add wave -noupdate /ult_tb/ULT/outer_tdc_hits
add wave -noupdate /ult_tb/ULT/extra_tdc_hits
add wave -noupdate /ult_tb/ULT/inn_segments_to_pt
add wave -noupdate /ult_tb/ULT/mid_segments_to_pt
add wave -noupdate /ult_tb/ULT/out_segments_to_pt
add wave -noupdate /ult_tb/ULT/ext_segments_to_pt
add wave -noupdate /ult_tb/ULT/inner_slc_to_pt
add wave -noupdate /ult_tb/ULT/middle_slc_to_pt
add wave -noupdate /ult_tb/ULT/outer_slc_to_pt
add wave -noupdate /ult_tb/ULT/extra_slc_to_pt
add wave -noupdate /ult_tb/ULT/pl2pt_av
add wave -noupdate /ult_tb/ULT/pl2mtc_av
add wave -noupdate /ult_tb/ULT/pt2mtc_av
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {1561732 fs} 0}
quietly wave cursor active 1
configure wave -namecolwidth 150
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {1561550 fs} {1562243 fs}
