onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /ult_tb/PRJ_INFO
add wave -noupdate /ult_tb/IN_SLC_FILE
add wave -noupdate /ult_tb/IN_HIT_FILE
add wave -noupdate /ult_tb/IN_CTRL_FILE
add wave -noupdate /ult_tb/g_ST_ENABLE
add wave -noupdate /ult_tb/DUMMY
add wave -noupdate /ult_tb/axi_rst
add wave -noupdate /ult_tb/clk_axi
add wave -noupdate /ult_tb/clk_axi_cnt
add wave -noupdate /ult_tb/clk_time
add wave -noupdate /ult_tb/tb_curr_time
add wave -noupdate /ult_tb/clk_tdc_time
add wave -noupdate /ult_tb/tb_curr_tdc_time
add wave -noupdate /ult_tb/clk_sim_time
add wave -noupdate /ult_tb/tb_curr_sim_time
add wave -noupdate /ult_tb/clk
add wave -noupdate /ult_tb/rst
add wave -noupdate /ult_tb/glob_en
add wave -noupdate /ult_tb/bx
add wave -noupdate /ult_tb/ttc_commands
add wave -noupdate /ult_tb/clock_and_control
add wave -noupdate /ult_tb/i_mdt_tdc_inn_av
add wave -noupdate /ult_tb/i_mdt_tdc_mid_av
add wave -noupdate /ult_tb/i_mdt_tdc_out_av
add wave -noupdate /ult_tb/i_mdt_tdc_ext_av
add wave -noupdate /ult_tb/i_main_primary_slc
add wave -noupdate /ult_tb/i_main_secondary_slc
add wave -noupdate /ult_tb/i_plus_neighbor_slc
add wave -noupdate /ult_tb/i_minus_neighbor_slc
add wave -noupdate /ult_tb/i_plus_neighbor_segments
add wave -noupdate /ult_tb/i_minus_neighbor_segments
add wave -noupdate /ult_tb/hps_inn_ctrl_r
add wave -noupdate /ult_tb/hps_inn_mon_r
add wave -noupdate /ult_tb/hps_mid_ctrl_r
add wave -noupdate /ult_tb/hps_mid_mon_r
add wave -noupdate /ult_tb/hps_out_ctrl_r
add wave -noupdate /ult_tb/hps_out_mon_r
add wave -noupdate /ult_tb/hps_ext_ctrl_r
add wave -noupdate /ult_tb/hps_ext_mon_r
add wave -noupdate /ult_tb/tar_inn_ctrl_r
add wave -noupdate /ult_tb/tar_inn_mon_r
add wave -noupdate /ult_tb/tar_mid_ctrl_r
add wave -noupdate /ult_tb/tar_mid_mon_r
add wave -noupdate /ult_tb/tar_out_ctrl_r
add wave -noupdate /ult_tb/tar_out_mon_r
add wave -noupdate /ult_tb/tar_ext_ctrl_r
add wave -noupdate /ult_tb/tar_ext_mon_r
add wave -noupdate /ult_tb/mtc_ctrl_r
add wave -noupdate /ult_tb/mtc_mon_r
add wave -noupdate /ult_tb/ucm_ctrl_r
add wave -noupdate /ult_tb/ucm_mon_r
add wave -noupdate /ult_tb/daq_ctrl_r
add wave -noupdate /ult_tb/daq_mon_r
add wave -noupdate /ult_tb/tf_ctrl_r
add wave -noupdate /ult_tb/tf_mon_r
add wave -noupdate /ult_tb/mpl_ctrl_r
add wave -noupdate /ult_tb/mpl_mon_r
add wave -noupdate /ult_tb/fm_ctrl_r
add wave -noupdate /ult_tb/fm_mon_r
add wave -noupdate /ult_tb/hps_inn_ctrl_v
add wave -noupdate /ult_tb/hps_inn_mon_v
add wave -noupdate /ult_tb/hps_mid_ctrl_v
add wave -noupdate /ult_tb/hps_mid_mon_v
add wave -noupdate /ult_tb/hps_out_ctrl_v
add wave -noupdate /ult_tb/hps_out_mon_v
add wave -noupdate /ult_tb/hps_ext_ctrl_v
add wave -noupdate /ult_tb/hps_ext_mon_v
add wave -noupdate /ult_tb/tar_inn_ctrl_v
add wave -noupdate /ult_tb/tar_inn_mon_v
add wave -noupdate /ult_tb/tar_mid_ctrl_v
add wave -noupdate /ult_tb/tar_mid_mon_v
add wave -noupdate /ult_tb/tar_out_ctrl_v
add wave -noupdate /ult_tb/tar_out_mon_v
add wave -noupdate /ult_tb/tar_ext_ctrl_v
add wave -noupdate /ult_tb/tar_ext_mon_v
add wave -noupdate /ult_tb/mtc_ctrl_v
add wave -noupdate /ult_tb/mtc_mon_v
add wave -noupdate /ult_tb/ucm_ctrl_v
add wave -noupdate /ult_tb/ucm_mon_v
add wave -noupdate /ult_tb/daq_ctrl_v
add wave -noupdate /ult_tb/daq_mon_v
add wave -noupdate /ult_tb/tf_ctrl_v
add wave -noupdate /ult_tb/tf_mon_v
add wave -noupdate /ult_tb/mpl_ctrl_v
add wave -noupdate /ult_tb/mpl_mon_v
add wave -noupdate /ult_tb/fm_ctrl_v
add wave -noupdate /ult_tb/fm_mon_v
add wave -noupdate /ult_tb/o_daq_streams
add wave -noupdate /ult_tb/o_plus_neighbor_segments
add wave -noupdate /ult_tb/o_minus_neighbor_segments
add wave -noupdate /ult_tb/o_MTC
add wave -noupdate /ult_tb/o_NSP
add wave -noupdate /ult_tb/slc_file_ok
add wave -noupdate /ult_tb/slc_file_ts
add wave -noupdate /ult_tb/mdt_file_ok
add wave -noupdate /ult_tb/mdt_file_ts
add wave -noupdate /ult_tb/slc_event_ai
add wave -noupdate /ult_tb/hit_mdt_event_ai
add wave -noupdate /ult_tb/hit_slc_event_ai
add wave -noupdate /ult_tb/sump
add wave -noupdate /ult_tb/c_CLK_AXI_MULT
add wave -noupdate /ult_tb/clk_time_period
add wave -noupdate /ult_tb/clk_tdc_time_period
add wave -noupdate /ult_tb/clk_sim_time_period
add wave -noupdate /ult_tb/clk_period
add wave -noupdate /ult_tb/reset_init_cycles
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {1398616601 fs} 0}
quietly wave cursor active 1
configure wave -namecolwidth 150
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {0 fs} {5250 ns}
