pkg:
	python3 ../../tools/yml2hdl/yml2hdl.py            \
		-e ../../shared/types/common_ieee.yml      \
		-e ../../shared/types/common_constants.yml \
		-e ../../dataformats/l0mdt_constants.yml   \
		-e ../../dataformats/l0mdt_dataformats.yml \
		-e ../../shared/types/common_types.yml     \
		ttc_defs.yml

