#################### mpl Project ###########################
generate_project:mpl:
    extends: .generate_project
    variables:
      extends: .vars
      PROJECT_NAME: mpl
      HOG_ONLY_SYNTH: 1 # if 1 runs only the synthesis

# simulate_project:mpl:
#     extends: .simulate_project
#     variables:
#       extends: .vars
#       PROJECT_NAME: mpl
