#################### ull_ku15_b3a_ucm_mpl_hps_csf_ptmpi Project ###########################
GEN:ull_ku15_b3a_ucm_mpl_hps_csf_ptmpi:
    extends: .generate_project
    variables:
      extends: .vars
      PROJECT_NAME: ull_ku15_b3a_ucm_mpl_hps_csf_ptmpi
      HOG_ONLY_SYNTH: 1 # if 1 runs only the synthesis
      
    tags:
      - heavy-duty
      - hog

SIM:ull_ku15_b3a_ucm_mpl_hps_csf_ptmpi:
    extends: .simulate_project
    variables:
      extends: .vars
      PROJECT_NAME: ull_ku15_b3a_ucm_mpl_hps_csf_ptmpi
    allow_failure: false
    tags:
      - questa
      - hog
      
      
# sim_comp:ull_ku15_b3a_ucm_mpl_hps_csf_ptmpi:
#     extends: .simulate_project_comp
#     variables:
#       extends: .vars
#       PROJECT_NAME: ull_ku15_b3a_ucm_mpl_hps_csf_ptmpi


RIV:ull_ku15_b3a_ucm_mpl_hps_csf_ptmpi:
    extends: .riviera_sim
    variables:
      extends: .riviera_vars
      PROJECT_NAME: ull_ku15_b3a_ucm_mpl_hps_csf_ptmpi
      HOG_CHECK_PROJVER: 0
      HOG_PATH: "/opt/Xilinx/Vivado/2019.2/bin:/mnt/vd/Xilinx/Vivado/2019.2/bin:/afs/cern.ch/project/parc/riviera20214/bin/"
      HOG_SIMULATION_LIB_PATH: "/home/l0mdtel/RivieraLib"

CHK:ull_ku15_b3a_ucm_mpl_hps_csf_ptmpi:
  extends: .sim_check
  variables:
    extends: .vars
    PROJECT_NAME: ull_ku15_b3a_ucm_mpl_hps_csf_ptmpi
  needs: ["SIM:ull_ku15_b3a_ucm_mpl_hps_csf_ptmpi","RIV:ull_ku15_b3a_ucm_mpl_hps_csf_ptmpi"]