#################### ull_ku15_b3a_ucm_mpl_hps_csf_ptmpi Project ###########################
GEN:ull_ku15_b3a_ucm_mpl_hps_csf_ptmpi:
    extends: .generate_project
    variables:
      extends: .vars
      PROJECT_NAME: ull_ku15_b3a_ucm_mpl_hps_csf_ptmpi
      HOG_ONLY_SYNTH: 1 # if 1 runs only the synthesis
      
    tags:
      - heavy-duty
      - hog

SIM:ull_ku15_b3a_ucm_mpl_hps_csf_ptmpi:
    extends: .simulate_project
    variables:
      extends: .vars
      PROJECT_NAME: ull_ku15_b3a_ucm_mpl_hps_csf_ptmpi
    allow_failure: false
    before_script:
      - export PATH="/opt/Xilinx/Vivado/2019.2/bin:/opt/questa/2019.4_4/questasim/linux_x86_64:$PATH"
    tags:
      - questa
      - hog
      
      
# sim_comp:ull_ku15_b3a_ucm_mpl_hps_csf_ptmpi:
#     extends: .simulate_project_comp
#     variables:
#       extends: .vars
#       PROJECT_NAME: ull_ku15_b3a_ucm_mpl_hps_csf_ptmpi

