#################### ull_ku15_b3a_ucm_mpl_hps Project ###########################
GEN:ull_ku15_b3a_ucm_mpl_hps:
    extends: .generate_project
    variables:
      extends: .vars
      PROJECT_NAME: ull_ku15_b3a_ucm_mpl_hps
      HOG_ONLY_SYNTH: 1 # if 1 runs only the synthesis
      HOG_CHECK_SYNTAX : 1
    tags:
      - normal-ops
      - hog

SIM:ull_ku15_b3a_ucm_mpl_hps:
    extends: .simulate_project
    variables:
      extends: .vars
      PROJECT_NAME: ull_ku15_b3a_ucm_mpl_hps
    allow_failure: false
    tags:
      - normal-ops
      - hog
      
# sim_comp:ull_ku15_b3a_ucm_mpl_hps:
#     extends: .simulate_project_comp
#     variables:
#       extends: .vars
#       PROJECT_NAME: ull_ku15_b3a_ucm_mpl_hps

