#################### ult_tp_dev Project ###########################
generate_project:ult_tp_dev:
    extends: .generate_project
    variables:
      extends: .vars
      PROJECT_NAME: ult_tp_dev
      HOG_ONLY_SYNTH: 1 # if 1 runs only the synthesis

simulate_project:ult_tp_dev:
    extends: .simulate_project
    variables:
      extends: .vars
      PROJECT_NAME: ult_tp_dev
    allow_failure: false

# sim_comp:ult_tp_dev:
#     extends: .sim_comp
#     variables:
#       extends: .vars
#       PROJECT_NAME: ult_tp_dev

