#################### ull_ku15_b3a_ucm_mpl_hps Project ###########################
GEN:ull_ku15_b3a_ucm_mpl_hps:
    extends: .generate_project
    variables:
      extends: .vars
      PROJECT_NAME: ull_ku15_b3a_ucm_mpl_hps
      HOG_ONLY_SYNTH: 1 # if 1 runs only the synthesis
      
    tags:
      - normal-ops
      - hog

SIM:ull_ku15_b3a_ucm_mpl_hps:
    extends: .simulate_project
    variables:
      extends: .vars
      PROJECT_NAME: ull_ku15_b3a_ucm_mpl_hps
    allow_failure: false
    tags:
      - questa
      - hog

RIV:ull_ku15_b3a_ucm_mpl_hps:
    extends: .riviera_sim
    variables:
      extends: .riviera_vars
      PROJECT_NAME: ull_ku15_b3a_ucm_mpl_hps
      HOG_CHECK_PROJVER: 0
      
CHK:ull_ku15_b3a_ucm_mpl_hps:
  extends: .sim_check
  variables:
    extends: .vars
    PROJECT_NAME: ull_ku15_b3a_ucm_mpl_hps
  needs: ["SIM:ull_ku15_b3a_ucm_mpl_hps","RIV:ull_ku15_b3a_ucm_mpl_hps"]

# sim_comp:ull_ku15_b3a_ucm_mpl_hps:
#     extends: .simulate_project_comp
#     variables:
#       extends: .vars
#       PROJECT_NAME: ull_ku15_b3a_ucm_mpl_hps

