// This file was auto-generated by YML2HDL toll.
// https://gitlab.com/tcpaiva/yml2hdl

`ifndef DAQ_DEFS_SVH
`define DAQ_DEFS_SVH

`include <common_defs.svh>

`include <ttc_defs.svh>

`include <daq_devel_defs.svh>


  typedef logic [DAQ_MAX_DATA_WIDTH-1:0] daq_stream_data_t;

  typedef struct packed {
    bcid_t   bcid;
    logic  valid;
    daq_stream_data_t   data;
  } daq_stream_rt;

  typedef daq_stream_rt  [DAQ_MAX_STREAMS-1:0] daq_branch_t;

  typedef int  daq_branch_struct_t [0:DAQ_MAX_STREAMS-1];



  typedef struct packed {
    logic  clk320;
    logic  rst;
  } daq_sys_rt;

  // daq_hdr_swrod_rt:
  // Fields required by swROD
  typedef struct packed {
    // flag_0: example of flag from swROD
    logic [8-1:0] flag_0;
    logic [8-1:0] flag_1;
    logic [16-1:0] flag_2;
    evid_t   evid;
  } daq_hdr_swrod_rt;

  typedef struct packed {
    bcid_t   daq_bcid;
    bcid_t   win_start;
    bcid_t   win_width;
    bcid_t   latency_ref;
    bcid_t   win_lower_ref;
    bcid_t   win_upper_ref;
    bcid_t   bcid;
  } daq_hdr_extra_rt;

  typedef struct packed {
    daq_hdr_swrod_rt   swrod;
    daq_hdr_extra_rt   extra;
  } daq_hdr_rt;

  typedef logic [$bits(daq_hdr_rt)-1:0] daq_hdr_vt;

  typedef struct packed {
    bcid_t   daq_bcid;
    bcid_t   win_start;
  } daq_cnt_rt;

  typedef struct packed {
    logic  win_upper;
    logic  win_lower;
    logic  latency;
  } stability_rt;

  typedef logic [$bits(stability_rt)-1:0] stability_vt;

  typedef struct packed {
    bcid_t   upper;
    bcid_t   lower;
    bcid_t   latency;
    bcid_t   width;
  } daq_win_rt;

  typedef logic [DAQ_MAX_DATA_WIDTH-1:0] pbldr_payload_t;

  typedef struct packed {
    logic  nempty;
    logic [DAQ_MAX_DATA_WIDTH-1:0] data;
  } forward_rt;

  typedef struct packed {
    logic  rd_strb;
  } backward_rt;

  typedef struct packed {
    logic  wr_en;
    logic [DAQ_MAX_DATA_WIDTH-1:0] data;
  } src_to_node_fifo_rt;

  typedef struct packed {
    logic  full;
  } node_fifo_to_src_rt;

  typedef logic [DAQ_MAX_COUNTER_WIDTH-1:0] node_fifo_cnt_t;

  typedef struct packed {
    daq_stream_data_t   data;
    node_fifo_cnt_t   count;
    logic  nempty;
  } node_fifo_to_dst_rt;

  typedef struct packed {
    logic  rd_en;
  } dst_to_node_fifo_rt;

  typedef struct packed {
    daq_sys_rt   sys;
    src_to_node_fifo_rt   src;
    dst_to_node_fifo_rt   dst;
  } daq_node_fifo_irt;

  typedef struct packed {
    node_fifo_to_src_rt   src;
    node_fifo_to_dst_rt   dst;
  } daq_node_fifo_ort;

  typedef struct packed {
    daq_node_fifo_irt   i;
    daq_node_fifo_ort   o;
  } daq_node_fifo_ert;

  typedef struct packed {
    int  WRITE_DATA_WIDTH;
    int  READ_DATA_WIDTH;
    int  READ_COUNT_WIDTH;
  } daq_node_fifo_grt;

  typedef struct packed {
    logic [DAQ_MAX_PIPELINES-1:0] done;
    logic [DAQ_MAX_PIPELINES-1:0] nempty;
    logic [DAQ_MAX_PIPELINES-1:0] err;
  } row_to_mngt_rt;

  typedef struct packed {
    logic [0:DAQ_MAX_PIPELINES-1] en;
    logic [0:DAQ_MAX_PIPELINES-1] rd_en;
  } mngt_to_row_rt;

  typedef struct packed {
    logic  en;
  } mngt_to_pbldr_rt;

  typedef struct packed {
    logic  done;
  } pbldr_to_mngt_rt;

  typedef struct packed {
    forward_rt   payload;
  } row_to_pbldr_rt;

  typedef struct packed {
    backward_rt   payload;
    logic  sel;
  } pbldr_to_row_rt;

  typedef struct packed {
    backward_rt   payload;
    logic [0:DAQ_MAX_ROWS-1] sel;
  } pbldr_to_rows_rt;

  typedef struct packed {
    logic  strb;
    bcid_t   win_start;
    bcid_t   win_width;
  } req_to_row_common_rt;

  typedef struct packed {
    bcid_t   latency;
    bcid_t   win_lower;
    bcid_t   win_upper;
    bcid_t   daq_bcid;
    bcid_t   bcid;
    evid_t   evid;
  } req_to_row_extra_rt;

  typedef struct packed {
    req_to_row_common_rt   common;
    req_to_row_extra_rt   extra;
  } req_to_row_rt;

  typedef struct packed {
    logic  hfull;
  } felix_to_daq_rt;

  typedef logic [DAQ_MAX_DATA_WIDTH-1:0] felix_data_t;

  typedef struct packed {
    logic  wr_en;
    felix_data_t   data;
  } daq_to_felix_rt;

  typedef struct packed {
    logic  wr_en;
    bcid_t   latency;
    bcid_t   win_lower;
    bcid_t   win_upper;
  } ctrl_to_daq_rt;

  typedef struct packed {
    stability_rt   stability;
  } daq_to_status_rt;

  typedef struct packed {
    stability_rt   stability;
  } daq_req_status_rt;

  typedef struct packed {
    daq_sys_rt   sys;
    ttc_ort   ttc;
    ctrl_to_daq_rt   ctrl;
  } daq_req_irt;

  typedef struct packed {
    daq_req_status_rt   status;
    req_to_row_rt   row;
  } daq_req_ort;

  typedef struct packed {
    daq_req_irt   i;
    daq_req_ort   o;
  } daq_req_ert;

  typedef logic [$bits(daq_req_irt)-1:0] daq_req_ivt;

  typedef logic [$bits(daq_req_ort)-1:0] daq_req_ovt;

  typedef struct packed {
    int  PIPELINES;
    int  INPUT_DATA_WIDTH;
    int  COUNTER_WIDTH;
  } daq_row_grt;

  typedef struct packed {
    daq_sys_rt   sys;
    mngt_to_row_rt   mngt;
    req_to_row_rt   req;
    pbldr_to_row_rt   pbldr;
  } daq_hrow_irt;

  typedef struct packed {
    daq_sys_rt   sys;
    mngt_to_row_rt   mngt;
    req_to_row_common_rt   req;
    daq_stream_rt   stream;
    pbldr_to_row_rt   pbldr;
  } daq_drow_irt;

  typedef struct packed {
    row_to_mngt_rt   mngt;
    row_to_pbldr_rt   pbldr;
  } daq_row_ort;

  typedef struct packed {
    daq_hrow_irt   i;
    daq_row_ort   o;
  } daq_hrow_ert;

  typedef struct packed {
    daq_drow_irt   i;
    daq_row_ort   o;
  } daq_drow_ert;

  typedef logic [$bits(daq_hrow_irt)-1:0] daq_hrow_ivt;

  typedef logic [$bits(daq_drow_irt)-1:0] daq_drow_ivt;

  typedef logic [$bits(daq_row_ort)-1:0] daq_row_ovt;

  typedef struct packed {
    daq_sys_rt   sys;
    mngt_to_pbldr_rt   mngt;
    row_to_pbldr_rt   row;
    felix_to_daq_rt   f2e;
  } daq_pbldr_irt;

  typedef struct packed {
    pbldr_to_rows_rt   row;
    daq_to_felix_rt   f2e;
  } daq_pbldr_ort;

  typedef struct packed {
    daq_pbldr_irt   i;
    daq_pbldr_ort   o;
  } daq_pbldr_ert;

  typedef logic [$bits(daq_pbldr_irt)-1:0] daq_pbldr_ivt;

  typedef logic [$bits(daq_pbldr_ort)-1:0] daq_pbldr_ovt;

  typedef struct packed {
    int  STREAMS;
    int  PIPELINES;
  } daq_mngt_grt;

  typedef struct packed {
    daq_sys_rt   sys;
    ttc_ort   ttc;
    row_to_mngt_rt   row;
  } daq_mngt_irt;

  typedef struct packed {
    mngt_to_row_rt   row;
    mngt_to_pbldr_rt   pbldr;
    logic [DAQ_MAX_PIPELINES-1:0] err;
  } daq_mngt_ort;

  typedef struct packed {
    daq_mngt_irt   i;
    daq_mngt_ort   o;
  } daq_mngt_ert;

  typedef logic [$bits(daq_mngt_irt)-1:0] daq_mngt_ivt;

  typedef logic [$bits(daq_mngt_ort)-1:0] daq_mngt_ovt;

  typedef struct {
    int  PIPELINES;
    daq_branch_struct_t   BRANCH_STRUCT;
    int  COUNTER_WIDTH;
  } daq_algo_grt;

  typedef struct packed {
    daq_sys_rt   sys;
    ttc_ort   ttc;
    ctrl_to_daq_rt   ctrl;
    daq_branch_t   branch;
    felix_to_daq_rt   f2e;
  } daq_algo_irt;

  typedef struct packed {
    daq_to_status_rt   status;
    daq_to_felix_rt   f2e;
  } daq_algo_ort;

  typedef struct packed {
    daq_algo_irt   i;
    daq_algo_ort   o;
  } daq_algo_ert;

  typedef logic [$bits(daq_algo_grt)-1:0] daq_algo_gvt;

  typedef logic [$bits(daq_algo_irt)-1:0] daq_algo_ivt;

  typedef logic [$bits(daq_algo_ort)-1:0] daq_algo_ovt;

  typedef felix_to_daq_rt  [0:DAQ_MAX_BRANCHES-1] mfelix_to_top_at;

  typedef daq_to_felix_rt  [0:DAQ_MAX_BRANCHES-1] top_to_mfelix_at;

  typedef daq_to_status_rt  [DAQ_MAX_BRANCHES-1:0] top_to_status_at;

  typedef struct {
    int  PIPELINES;
    daq_branches_map_at   BRANCHES_STRUCT;
    int  COUNTER_WIDTH;
  } daq_top_grt;

  typedef struct packed {
    daq_sys_rt   sys;
    ttc_ort   ttc;
    ctrl_to_daq_rt   ctrl;
    daq_branches_t   branches;
    mfelix_to_top_at   f2e_bus;
  } daq_top_irt;

  typedef struct packed {
    top_to_status_at   status_bus;
    top_to_mfelix_at   f2e_bus;
  } daq_top_ort;

  typedef struct packed {
    daq_top_irt   i;
    daq_top_ort   o;
  } daq_top_ert;

  typedef logic [$bits(daq_top_grt)-1:0] daq_top_gvt;

  typedef logic [$bits(daq_top_irt)-1:0] daq_top_ivt;

  typedef logic [$bits(daq_top_ort)-1:0] daq_top_ovt;

  typedef struct packed {
    ttc_sys_rt   sys;
    ttc_fmt_vt   ttc;
    ctrl_to_daq_rt   ctrl;
    daq_stream_rt   stream_0;
    daq_stream_rt   stream_1;
    daq_stream_rt   stream_2;
    daq_stream_rt   stream_3;
    daq_stream_rt   stream_4;
    daq_stream_rt   stream_5;
    daq_stream_rt   stream_6;
    daq_stream_rt   stream_7;
    daq_stream_rt   stream_8;
    felix_to_daq_rt   f2e0;
    felix_to_daq_rt   f2e1;
  } daq_usr_irt;

  typedef struct packed {
    daq_to_status_rt   status0;
    daq_to_status_rt   status1;
    daq_to_felix_rt   f2e0;
    daq_to_felix_rt   f2e1;
  } daq_usr_ort;

  typedef struct packed {
    daq_usr_irt   i;
    daq_usr_ort   o;
  } daq_usr_ert;



`endif // DAQ_DEFS_SVH
