create_project:pt:
    extends: .create_project
    variables:
      extends: .vars
      PROJECT_NAME: pt

simulate_project:pt:
    extends: .simulate_project
    variables:
      extends: .vars
      PROJECT_NAME: pt

synthesise_ips:pt:
    extends: .synthesise_ips
    variables:
      extends: .vars
      PROJECT_NAME: pt
      IP_PATH: IP
    dependencies:
        - create_project:pt

synthesise_project:pt:
    extends: .synthesise_project
    variables:
      extends: .vars
      PROJECT_NAME: pt
    dependencies:
        - synthesise_ips:pt
        - create_project:pt

implement_project:pt:
    extends: .implement_project
    variables:
      extends: .vars
      PROJECT_NAME: pt
    dependencies:
       - create_project:pt
       - synthesise_ips:pt
       - synthesise_project:pt

# write_bitstream:pt:
#     extends: .write_bitstream
#     variables:
#       extends: .vars
#       PROJECT_NAME: pt
#     dependencies:
#        - create_project:pt
#        - synthesise_ips:pt
#        - synthesise_project:pt
#        - implement_project:pt
