#################### ult_tp Project ###########################
generate_project:ult_tp:
    extends: .generate_project
    variables:
      extends: .vars
      PROJECT_NAME: ult_tp
      HOG_ONLY_SYNTH: 1 # if 1 runs only the synthesis

simulate_project:ult_tp:
    extends: .simulate_project
    variables:
      extends: .vars
      PROJECT_NAME: ult_tp
