#################### ull_vu13p/ull_vu13_b3a_ucm_mpl Project ###########################
GEN:ull_vu13_b3a_ucm_mpl:
    extends: .generate_project
    variables:
      extends: .vars
      PROJECT_NAME: ull_vu13p/ull_vu13_b3a_ucm_mpl
      HOG_ONLY_SYNTH: 1 # if 1 runs only the synthesis
      
    tags:
      - normal-ops

SIM:ull_vu13_b3a_ucm_mpl:
    extends: .simulate_project
    variables:
      extends: .vars
      PROJECT_NAME: ull_vu13p/ull_vu13_b3a_ucm_mpl
      HOG_CHECK_PROJVER: 0

    tags:
      - normal-ops
    allow_failure: false
    
# user_sim:ull_vu13_b3a_ucm_mpl:
#     extends: .user_sim
#     variables:
#       extends: .vars
#       PROJECT_NAME: ull_vu13_b3a_ucm_mpl


# RIV:ull_vu13_b3a_ucm_mpl:
#     extends: .riviera_sim
#     variables:
#       extends: .riviera_vars
#       PROJECT_NAME: ull_vu13_b3a_ucm_mpl
#       HOG_CHECK_PROJVER: 0
#       # HOG_PATH: "/opt/Xilinx/Vivado/2019.2/bin:/mnt/vd/Xilinx/Vivado/2019.2/bin:/afs/cern.ch/project/parc/riviera20214/bin/"
#       HOG_SIMULATION_LIB_PATH: "/home/l0mdtel/RivieraLib"
#     before_script:
#       - export PATH="/opt/Xilinx/Vivado/2019.2/bin:/opt/Aldec/Riviera-PRO-2021.04-x64/bin:$PATH"


# CHK:ull_vu13_b3a_ucm_mpl:
#   extends: .sim_check
#   variables:
#     extends: .vars
#     PROJECT_NAME: ull_vu13_b3a_ucm_mpl
#   needs: ["SIM:ull_vu13_b3a_ucm_mpl","RIV:ull_vu13_b3a_ucm_mpl"]
