#################### ptc_mpi Project ###########################
GEN:ptc_mpi:
    extends: .GEN
    variables:
      extends: .vars
      PROJECT_NAME: ptc_mpi
      HOG_ONLY_SYNTH: 1 # if 1 runs only the synthesis

SIM:ptc_mpi:
    extends: .SIM
    variables:
      extends: .vars
      PROJECT_NAME: ptc_mpi
