#################### ptc_mpi Project ###########################
GEN:ptc_mpi:
    extends: .generate_project
    variables:
      extends: .vars
      PROJECT_NAME: ptc_mpi
      HOG_ONLY_SYNTH: 1 # if 1 runs only the synthesis
    tags:
      - normal-ops
      - hog

SIM:ptc_mpi:
    extends: .simulate_project
    variables:
      extends: .vars
      PROJECT_NAME: ptc_mpi
    before_script:
      - export PATH="/opt/Xilinx/Vivado/2019.2/bin:/opt/questa/2019.4_4/questasim/linux_x86_64:$PATH"
    tags:
      - questa
      - hog
      
