#################### ptc_mpi Project ###########################
# GEN:ptc_mpi:
#     extends: .generate_project
#     variables:
#       extends: .vars
#       PROJECT_NAME: ptc_mpi
#       HOG_ONLY_SYNTH: 1 # if 1 runs only the synthesis
#     tags:
#       - normal-ops
#       - hog

SIM:ptc_mpi:
    extends: .simulate_project
    variables:
      extends: .vars
      PROJECT_NAME: ptc_mpi
    tags:
      - questa
      - hog
      - "2020.2"
      
CHK:ptc_mpi:
  extends: .sim_check
  variables: 
    extends: .vars
    PROJECT_NAME: ptc_mpi
    BLOCK: PTC
  needs: ["SIM:ptc_mpi"]
  artifacts:
    name: CHK_ptc
    paths:
      - $CI_PROJECT_DIR/bin
    expire_in: 30 day