#################### ull_ku15_b3a_ucm_mpl_hps_lsf Project ###########################
GEN:ull_ku15_b3a_ucm_mpl_hps_lsf:
    extends: .generate_project
    variables:
      extends: .vars
      PROJECT_NAME: ull_ku15_b3a_ucm_mpl_hps_lsf
      HOG_ONLY_SYNTH: 1 # if 1 runs only the synthesis
      
    tags:
      - heavy-duty
      - hog

SIM:ull_ku15_b3a_ucm_mpl_hps_lsf:
    extends: .simulate_project
    variables:
      extends: .vars
      PROJECT_NAME: ull_ku15_b3a_ucm_mpl_hps_lsf
    allow_failure: false
    tags:
      - questa
      - hog
      
# sim_comp:ull_ku15_b3a_ucm_mpl_hps_lsf:
#     extends: .simulate_project_comp
#     variables:
#       extends: .vars
#       PROJECT_NAME: ull_ku15_b3a_ucm_mpl_hps_lsf


RIV:ull_ku15_b3a_ucm_mpl_hps_lsf:
    extends: .riviera_sim
    variables:
      extends: .riviera_vars
      PROJECT_NAME: ull_ku15_b3a_ucm_mpl_hps_lsf
      HOG_CHECK_PROJVER: 0

CHK:ull_ku15_b3a_ucm_mpl_hps_lsf:
  extends: .sim_check
  variables:
    extends: .vars
    PROJECT_NAME: ull_ku15_b3a_ucm_mpl_hps_lsf
  needs: ["SIM:ull_ku15_b3a_ucm_mpl_hps_lsf","RIV:ull_ku15_b3a_ucm_mpl_hps_lsf"]