#################### l0mdt Project ###########################
GEN:base_l0mdt:
    extends: .generate_project
    variables:
      extends: .vars
      PROJECT_NAME: base_l0mdt
      HOG_ONLY_SYNTH: 1 # if 1 runs only the synthesis
      HOG_CHECK_SYNTAX: 0
      HOG_NO_BITSTREAM: 0
    tags:
      - heavy-duty
    artifacts:
      when: always
        name: implementation_and_bitfiles
        paths:
          - bin 
      when: on_failure
        paths:
          - Projects


CHK:base_l0mdt:
    extends: .check_list_and_conf
    variables:
      extends: .vars
      PROJECT_NAME: base_l0mdt
